import { formatCurrency, formatNumber } from "@/lib/formatters";
import type { ModuleConfig } from "@/features/shared/components/management/types";

const payrollStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Đã tính", value: "calculated" },
  { label: "Đang rà soát", value: "reviewing" },
  { label: "Đã duyệt", value: "approved" },
  { label: "Đã khóa", value: "locked" },
  { label: "Đã trả", value: "paid" },
  { label: "Đã hủy", value: "cancelled" },
];

const policyStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Đang áp dụng", value: "active" },
  { label: "Ngưng áp dụng", value: "inactive" },
  { label: "Lưu trữ", value: "archived" },
];

const taxabilityOptions = [
  { label: "Chịu thuế", value: "taxable" },
  { label: "Miễn thuế", value: "non_taxable" },
];

const contractTypeOptions = [
  { label: "Full-time", value: "full_time" },
  { label: "Part-time", value: "part_time" },
  { label: "Thử việc", value: "probation" },
  { label: "Cộng tác viên", value: "contractor" },
  { label: "Khác", value: "other" },
];

const salaryPaymentTypeOptions = [
  { label: "Gross", value: "gross" },
  { label: "Net", value: "net" },
];

export const payrollModules: ModuleConfig[] = [
  {
    key: "payroll-periods",
    title: "Kỳ lương",
    description: "Tạo kỳ lương, chọn policy có hiệu lực, tính lương, duyệt, khóa và đánh dấu đã thanh toán.",
    primaryAction: "Tạo kỳ lương",
    apiPath: "/api/payroll-periods",
    searchPlaceholder: "Tìm mã kỳ lương, policy hoặc ghi chú...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "periodCode", label: "Mã kỳ", sortable: true, width: "150px" },
      { key: "periodStart", label: "Từ ngày", sortable: true, format: "date", width: "130px" },
      { key: "periodEnd", label: "Đến ngày", sortable: true, format: "date", width: "130px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "150px" },
      { key: "lineCount", label: "Số NV", width: "110px" },
      { key: "grossAmount", label: "Tổng gross", sortable: true, format: "money", width: "170px" },
      { key: "bankTransferAmount", label: "Chuyển khoản", sortable: true, format: "money", width: "170px" },
      { key: "calculatedAt", label: "Đã tính", format: "date", width: "130px" },
      { key: "lockedAt", label: "Đã khóa", format: "date", width: "130px" },
    ],
    filters: [{ key: "status", label: "Trạng thái", type: "select", options: payrollStatusOptions }],
    fields: [
      { key: "periodCode", label: "Mã kỳ lương", type: "text", required: true, section: "Kỳ lương" },
      { key: "periodStart", label: "Từ ngày", type: "date", required: true, section: "Kỳ lương" },
      { key: "periodEnd", label: "Đến ngày", type: "date", required: true, section: "Kỳ lương" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: payrollStatusOptions },
      { key: "payrollPolicyVersionId", label: "Chính sách lương", type: "select", section: "Policy áp dụng", lookupKey: "payrollPolicies" },
      { key: "taxPolicyVersionId", label: "Chính sách thuế", type: "select", section: "Policy áp dụng", lookupKey: "taxPolicies" },
      { key: "insurancePolicyVersionId", label: "Chính sách bảo hiểm", type: "select", section: "Policy áp dụng", lookupKey: "insurancePolicies" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "periodCode", label: "Mã kỳ" },
      { key: "periodStart", label: "Từ ngày", format: "date" },
      { key: "periodEnd", label: "Đến ngày", format: "date" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "payrollPolicyVersionName", label: "Chính sách lương" },
      { key: "taxPolicyVersionName", label: "Chính sách thuế" },
      { key: "insurancePolicyVersionName", label: "Chính sách bảo hiểm" },
      { key: "lineCount", label: "Số nhân viên" },
      { key: "grossAmount", label: "Tổng gross", format: "money" },
      { key: "bankTransferAmount", label: "Chuyển khoản", format: "money" },
      { key: "calculatedAt", label: "Đã tính", format: "date" },
      { key: "approvedAt", label: "Đã duyệt", format: "date" },
      { key: "lockedAt", label: "Đã khóa", format: "date" },
      { key: "paidAt", label: "Đã trả", format: "date" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng kỳ", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Gross trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.grossAmount ?? 0), 0)) },
      { label: "CK trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.bankTransferAmount ?? 0), 0)) },
    ],
    rowActions: [
      { key: "calculate", label: "Tính lương", icon: "play", endpoint: (record) => `/api/payroll-periods/${record.id}/calculate`, confirmTitle: "Tính lương kỳ này", confirmLabel: "Tính", hidden: (record) => ["locked", "paid", "cancelled"].includes(String(record.status)) },
      { key: "review", label: "Rà soát", icon: "send", endpoint: (record) => `/api/payroll-periods/${record.id}/review`, confirmLabel: "Rà soát", hidden: (record) => record.status !== "calculated" },
      { key: "approve", label: "Duyệt", icon: "check", variant: "success", endpoint: (record) => `/api/payroll-periods/${record.id}/approve`, confirmLabel: "Duyệt", hidden: (record) => !["calculated", "reviewing"].includes(String(record.status)) },
      { key: "lock", label: "Khóa", icon: "lock", variant: "warning", endpoint: (record) => `/api/payroll-periods/${record.id}/lock`, confirmLabel: "Khóa", hidden: (record) => record.status !== "approved" },
      { key: "pay", label: "Đã trả", icon: "dollar", variant: "success", endpoint: (record) => `/api/payroll-periods/${record.id}/pay`, confirmLabel: "Đã trả", hidden: (record) => record.status !== "locked" },
      { key: "cancel", label: "Hủy", icon: "x", variant: "danger", endpoint: (record) => `/api/payroll-periods/${record.id}/cancel`, confirmLabel: "Hủy", hidden: (record) => !["draft", "calculated", "reviewing"].includes(String(record.status)) },
    ],
  },
  {
    key: "payroll-inputs",
    title: "Input kỳ lương",
    description: "Quản lý ngày công, doanh số, tạm ứng, hoàn ứng và điều chỉnh theo từng nhân viên trong kỳ.",
    primaryAction: "Thêm input",
    apiPath: "/api/payroll-inputs",
    searchPlaceholder: "Tìm kỳ lương, mã NV, tên nhân viên...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "periodCode", label: "Kỳ", sortable: true, width: "140px" },
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "220px" },
      { key: "actualWorkdays", label: "Công", sortable: true, width: "100px" },
      { key: "revenueAmount", label: "Doanh số", sortable: true, format: "money", width: "160px" },
      { key: "oneTimeJobRevenueAmount", label: "Job 1 lần", format: "money", width: "160px" },
      { key: "advanceAmount", label: "Tạm ứng", sortable: true, format: "money", width: "150px" },
      { key: "reimbursementAmount", label: "Hoàn ứng", format: "money", width: "150px" },
      { key: "taxableAdjustmentAmount", label: "ĐC chịu thuế", format: "money", width: "160px" },
      { key: "nonTaxableAdjustmentAmount", label: "ĐC miễn thuế", format: "money", width: "160px" },
    ],
    filters: [
      { key: "payrollPeriodId", label: "Kỳ lương", type: "select", lookupKey: "payrollPeriods" },
      { key: "employeeId", label: "Nhân viên", type: "select", lookupKey: "employees" },
    ],
    fields: [
      { key: "payrollPeriodId", label: "Kỳ lương", type: "select", required: true, section: "Liên kết", lookupKey: "payrollPeriods" },
      { key: "employeeId", label: "Nhân viên", type: "select", required: true, section: "Liên kết", lookupKey: "employees" },
      { key: "actualWorkdays", label: "Ngày công thực tế", type: "number", section: "Ngày công" },
      { key: "unpaidLeaveDays", label: "Nghỉ không lương", type: "number", section: "Ngày công" },
      { key: "overtimeHours", label: "Giờ tăng ca", type: "number", section: "Ngày công" },
      { key: "revenueAmount", label: "Doanh số", type: "number", section: "Doanh số" },
      { key: "exceededRevenueAmount", label: "Doanh số vượt", type: "number", section: "Doanh số" },
      { key: "oneTimeJobRevenueAmount", label: "Doanh số job 1 lần", type: "number", section: "Doanh số" },
      { key: "newCustomerRevenueAmount", label: "Doanh số khách mới", type: "number", section: "Doanh số" },
      { key: "advanceAmount", label: "Tạm ứng", type: "number", section: "Điều chỉnh" },
      { key: "reimbursementAmount", label: "Hoàn ứng", type: "number", section: "Điều chỉnh" },
      { key: "taxableAdjustmentAmount", label: "Điều chỉnh chịu thuế", type: "number", section: "Điều chỉnh" },
      { key: "nonTaxableAdjustmentAmount", label: "Điều chỉnh miễn thuế", type: "number", section: "Điều chỉnh" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "periodCode", label: "Kỳ" },
      { key: "employeeName", label: "Nhân viên" },
      { key: "actualWorkdays", label: "Ngày công" },
      { key: "revenueAmount", label: "Doanh số", format: "money" },
      { key: "oneTimeJobRevenueAmount", label: "Job 1 lần", format: "money" },
      { key: "advanceAmount", label: "Tạm ứng", format: "money" },
      { key: "reimbursementAmount", label: "Hoàn ứng", format: "money" },
      { key: "taxableAdjustmentAmount", label: "ĐC chịu thuế", format: "money" },
      { key: "nonTaxableAdjustmentAmount", label: "ĐC miễn thuế", format: "money" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng input", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Doanh số trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.revenueAmount ?? 0), 0)) },
      { label: "Tạm ứng trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.advanceAmount ?? 0), 0)) },
    ],
  },
  {
    key: "payroll-lines",
    title: "Bảng lương tổng",
    description: "Xem kết quả tính lương theo nhân viên, gồm gross/net, bảo hiểm, thuế, tạm ứng và chuyển khoản.",
    primaryAction: "Không dùng",
    apiPath: "/api/payroll-lines",
    searchPlaceholder: "Tìm kỳ lương, mã NV, tên nhân viên...",
    defaultSortBy: "createdAt",
    canCreate: false,
    canEdit: false,
    canDelete: false,
    columns: [
      { key: "periodCode", label: "Kỳ", sortable: true, width: "130px" },
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "220px" },
      { key: "departmentName", label: "Phòng ban", width: "160px" },
      { key: "salaryPaymentType", label: "Gross/Net", format: "status", width: "120px" },
      { key: "baseSalary", label: "Lương cơ bản", format: "money", width: "160px" },
      { key: "grossSalaryAmount", label: "Tổng lương", sortable: true, format: "money", width: "160px" },
      { key: "employeeInsuranceAmount", label: "BH NLĐ", format: "money", width: "150px" },
      { key: "personalIncomeTaxAmount", label: "Thuế TNCN", format: "money", width: "150px" },
      { key: "netSalaryAmount", label: "Thực nhận", format: "money", width: "160px" },
      { key: "bankTransferAmount", label: "Chuyển khoản", sortable: true, format: "money", width: "170px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
    ],
    filters: [
      { key: "payrollPeriodId", label: "Kỳ lương", type: "select", lookupKey: "payrollPeriods" },
      { key: "employeeId", label: "Nhân viên", type: "select", lookupKey: "employees" },
      { key: "status", label: "Trạng thái", type: "select", options: payrollStatusOptions },
    ],
    fields: [],
    detailFields: [
      { key: "periodCode", label: "Kỳ" },
      { key: "employeeName", label: "Nhân viên" },
      { key: "salaryPaymentType", label: "Gross/Net", format: "status" },
      { key: "baseSalary", label: "Lương cơ bản", format: "money" },
      { key: "standardWorkdays", label: "Công chuẩn" },
      { key: "actualWorkdays", label: "Công thực tế" },
      { key: "timeSalaryAmount", label: "Lương thời gian", format: "money" },
      { key: "nonTaxableIncomeAmount", label: "TN miễn thuế", format: "money" },
      { key: "taxableIncomeAmount", label: "TN chịu thuế", format: "money" },
      { key: "grossSalaryAmount", label: "Tổng lương", format: "money" },
      { key: "dependentCount", label: "Người phụ thuộc" },
      { key: "employeeInsuranceAmount", label: "BH NLĐ", format: "money" },
      { key: "personalIncomeTaxAmount", label: "Thuế TNCN", format: "money" },
      { key: "netSalaryAmount", label: "Thực nhận", format: "money" },
      { key: "advanceAmount", label: "Tạm ứng", format: "money" },
      { key: "reimbursementAmount", label: "Hoàn ứng", format: "money" },
      { key: "bankTransferAmount", label: "Chuyển khoản", format: "money" },
      { key: "employerInsuranceAmount", label: "BH doanh nghiệp", format: "money" },
      { key: "status", label: "Trạng thái", format: "status" },
    ],
    metrics: [
      { label: "Tổng dòng", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Gross trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.grossSalaryAmount ?? 0), 0)) },
      { label: "CK trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.bankTransferAmount ?? 0), 0)) },
    ],
  },
  {
    key: "payroll-policy-versions",
    title: "Chính sách lương",
    description: "Cấu hình ngày công chuẩn, gross-up và phiên bản chính sách lương theo hiệu lực.",
    primaryAction: "Thêm chính sách lương",
    apiPath: "/api/payroll-policy-versions",
    searchPlaceholder: "Tìm mã, tên chính sách...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "140px" },
      { key: "name", label: "Tên chính sách", sortable: true, width: "260px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "standardWorkdays", label: "Công chuẩn", width: "130px" },
      { key: "grossUpMethod", label: "Gross-up", width: "180px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "130px" },
      { key: "effectiveTo", label: "Kết thúc", format: "date", width: "130px" },
    ],
    filters: [{ key: "status", label: "Trạng thái", type: "select", options: policyStatusOptions }],
    fields: [
      { key: "code", label: "Mã chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "name", label: "Tên chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: policyStatusOptions },
      { key: "standardWorkdays", label: "Ngày công chuẩn", type: "number", section: "Cấu hình" },
      { key: "grossUpMethod", label: "Phương pháp gross-up", type: "text", section: "Cấu hình" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã" }, { key: "name", label: "Tên" }, { key: "status", label: "Trạng thái", format: "status" },
      { key: "standardWorkdays", label: "Ngày công chuẩn" }, { key: "grossUpMethod", label: "Gross-up" },
      { key: "effectiveFrom", label: "Hiệu lực từ", format: "date" }, { key: "effectiveTo", label: "Hiệu lực đến", format: "date" }, { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng chính sách", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang áp dụng", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
    ],
  },
  {
    key: "tax-policy-versions",
    title: "Chính sách thuế",
    description: "Cấu hình giảm trừ bản thân, người phụ thuộc và phương pháp tính thuế theo hiệu lực.",
    primaryAction: "Thêm chính sách thuế",
    apiPath: "/api/tax-policy-versions",
    searchPlaceholder: "Tìm mã, tên chính sách thuế...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "140px" },
      { key: "name", label: "Tên chính sách", sortable: true, width: "260px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "personalDeductionAmount", label: "Giảm trừ bản thân", format: "money", width: "180px" },
      { key: "dependentDeductionAmount", label: "Giảm trừ NPT", format: "money", width: "170px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "130px" },
    ],
    filters: [{ key: "status", label: "Trạng thái", type: "select", options: policyStatusOptions }],
    fields: [
      { key: "code", label: "Mã chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "name", label: "Tên chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: policyStatusOptions },
      { key: "personalDeductionAmount", label: "Giảm trừ bản thân", type: "number", section: "Chỉ số thuế" },
      { key: "dependentDeductionAmount", label: "Giảm trừ người phụ thuộc", type: "number", section: "Chỉ số thuế" },
      { key: "taxMethod", label: "Phương pháp thuế", type: "text", section: "Chỉ số thuế" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã" }, { key: "name", label: "Tên" }, { key: "status", label: "Trạng thái", format: "status" },
      { key: "personalDeductionAmount", label: "Giảm trừ bản thân", format: "money" }, { key: "dependentDeductionAmount", label: "Giảm trừ NPT", format: "money" },
      { key: "taxMethod", label: "Phương pháp" }, { key: "effectiveFrom", label: "Hiệu lực từ", format: "date" }, { key: "effectiveTo", label: "Hiệu lực đến", format: "date" },
    ],
    metrics: [
      { label: "Tổng chính sách", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang áp dụng", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Giảm trừ cao nhất", getValue: (records) => formatCurrency(Math.max(0, ...records.map((item) => Number(item.personalDeductionAmount ?? 0)))) },
    ],
  },
  {
    key: "tax-policy-brackets",
    title: "Bậc thuế TNCN",
    description: "Cấu hình biểu thuế lũy tiến theo từng chính sách thuế.",
    primaryAction: "Thêm bậc thuế",
    apiPath: "/api/tax-policy-brackets",
    searchPlaceholder: "Tìm theo chính sách thuế...",
    defaultSortBy: "bracketOrder",
    columns: [
      { key: "taxPolicyName", label: "Chính sách", sortable: true, width: "260px" },
      { key: "bracketOrder", label: "Bậc", sortable: true, width: "100px" },
      { key: "fromAmount", label: "Từ", sortable: true, format: "money", width: "150px" },
      { key: "toAmount", label: "Đến", format: "money", width: "150px" },
      { key: "taxRate", label: "Tỷ lệ", sortable: true, width: "120px" },
      { key: "quickDeductionAmount", label: "Giảm nhanh", format: "money", width: "160px" },
    ],
    filters: [{ key: "taxPolicyVersionId", label: "Chính sách thuế", type: "select", lookupKey: "taxPolicies" }],
    fields: [
      { key: "taxPolicyVersionId", label: "Chính sách thuế", type: "select", required: true, section: "Liên kết", lookupKey: "taxPolicies" },
      { key: "bracketOrder", label: "Thứ tự bậc", type: "number", required: true, section: "Bậc thuế" },
      { key: "fromAmount", label: "Từ mức", type: "number", section: "Bậc thuế" },
      { key: "toAmount", label: "Đến mức", type: "number", section: "Bậc thuế" },
      { key: "taxRate", label: "Tỷ lệ thuế", type: "number", section: "Bậc thuế" },
      { key: "quickDeductionAmount", label: "Giảm trừ nhanh", type: "number", section: "Bậc thuế" },
    ],
    detailFields: [
      { key: "taxPolicyName", label: "Chính sách" }, { key: "bracketOrder", label: "Bậc" },
      { key: "fromAmount", label: "Từ", format: "money" }, { key: "toAmount", label: "Đến", format: "money" },
      { key: "taxRate", label: "Tỷ lệ" }, { key: "quickDeductionAmount", label: "Giảm nhanh", format: "money" },
    ],
    metrics: [
      { label: "Tổng bậc", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Bậc cao nhất", getValue: (records) => formatNumber(Math.max(0, ...records.map((item) => Number(item.bracketOrder ?? 0)))) },
    ],
  },
  {
    key: "insurance-policy-versions",
    title: "Chính sách bảo hiểm",
    description: "Cấu hình tỷ lệ BHXH, BHYT, BHTN, KPCĐ theo phía doanh nghiệp và người lao động.",
    primaryAction: "Thêm chính sách BH",
    apiPath: "/api/insurance-policy-versions",
    searchPlaceholder: "Tìm mã, tên chính sách bảo hiểm...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "130px" },
      { key: "name", label: "Tên chính sách", sortable: true, width: "240px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "employeeSocialRate", label: "NLĐ BHXH", width: "130px" },
      { key: "employeeHealthRate", label: "NLĐ BHYT", width: "130px" },
      { key: "employeeUnemploymentRate", label: "NLĐ BHTN", width: "130px" },
      { key: "employerSocialRate", label: "DN BHXH", width: "130px" },
      { key: "employerHealthRate", label: "DN BHYT", width: "130px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "130px" },
    ],
    filters: [{ key: "status", label: "Trạng thái", type: "select", options: policyStatusOptions }],
    fields: [
      { key: "code", label: "Mã chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "name", label: "Tên chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: policyStatusOptions },
      { key: "employeeSocialRate", label: "NLĐ BHXH", type: "number", section: "Người lao động" },
      { key: "employeeHealthRate", label: "NLĐ BHYT", type: "number", section: "Người lao động" },
      { key: "employeeUnemploymentRate", label: "NLĐ BHTN", type: "number", section: "Người lao động" },
      { key: "employerSocialRate", label: "DN BHXH", type: "number", section: "Doanh nghiệp" },
      { key: "employerHealthRate", label: "DN BHYT", type: "number", section: "Doanh nghiệp" },
      { key: "employerUnemploymentRate", label: "DN BHTN", type: "number", section: "Doanh nghiệp" },
      { key: "employerUnionRate", label: "KPCĐ", type: "number", section: "Doanh nghiệp" },
      { key: "minInsuranceBase", label: "Sàn đóng BH", type: "number", section: "Trần/sàn" },
      { key: "maxInsuranceBase", label: "Trần đóng BH", type: "number", section: "Trần/sàn" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã" }, { key: "name", label: "Tên" }, { key: "status", label: "Trạng thái", format: "status" },
      { key: "employeeSocialRate", label: "NLĐ BHXH" }, { key: "employeeHealthRate", label: "NLĐ BHYT" }, { key: "employeeUnemploymentRate", label: "NLĐ BHTN" },
      { key: "employerSocialRate", label: "DN BHXH" }, { key: "employerHealthRate", label: "DN BHYT" }, { key: "employerUnemploymentRate", label: "DN BHTN" }, { key: "employerUnionRate", label: "KPCĐ" },
      { key: "minInsuranceBase", label: "Sàn", format: "money" }, { key: "maxInsuranceBase", label: "Trần", format: "money" },
    ],
    metrics: [
      { label: "Tổng chính sách", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang áp dụng", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
    ],
  },
  {
    key: "commission-policies",
    title: "Chính sách hoa hồng",
    description: "Cấu hình hoa hồng vượt doanh số, job một lần, khách mới theo nhóm nhân sự và hiệu lực.",
    primaryAction: "Thêm chính sách hoa hồng",
    apiPath: "/api/commission-policies",
    searchPlaceholder: "Tìm mã, tên, loại hoa hồng...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "130px" },
      { key: "name", label: "Tên chính sách", sortable: true, width: "230px" },
      { key: "commissionType", label: "Loại", sortable: true, width: "170px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "departmentName", label: "Phòng ban", width: "170px" },
      { key: "targetRevenueMultiplier", label: "Định mức x", width: "130px" },
      { key: "defaultRate", label: "Tỷ lệ", sortable: true, width: "120px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "130px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: policyStatusOptions },
      { key: "departmentId", label: "Phòng ban", type: "select", lookupKey: "departments" },
      { key: "jobLevelId", label: "Bậc", type: "select", lookupKey: "jobLevels" },
      { key: "contractType", label: "Loại HĐ", type: "select", options: contractTypeOptions },
      { key: "salaryPaymentType", label: "Gross/Net", type: "select", options: salaryPaymentTypeOptions },
    ],
    fields: [
      { key: "code", label: "Mã chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "name", label: "Tên chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "commissionType", label: "Loại hoa hồng", type: "text", required: true, section: "Thông tin" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: policyStatusOptions },
      { key: "departmentId", label: "Phòng ban", type: "select", section: "Phạm vi", lookupKey: "departments" },
      { key: "jobLevelId", label: "Bậc", type: "select", section: "Phạm vi", lookupKey: "jobLevels" },
      { key: "contractType", label: "Loại HĐ", type: "select", section: "Phạm vi", options: contractTypeOptions },
      { key: "salaryPaymentType", label: "Gross/Net", type: "select", section: "Phạm vi", options: salaryPaymentTypeOptions },
      { key: "targetRevenueMultiplier", label: "Định mức doanh số x lương", type: "number", section: "Công thức" },
      { key: "defaultRate", label: "Tỷ lệ mặc định", type: "number", section: "Công thức" },
      { key: "minRate", label: "Tỷ lệ min", type: "number", section: "Công thức" },
      { key: "maxRate", label: "Tỷ lệ max", type: "number", section: "Công thức" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
    ],
    detailFields: [
      { key: "code", label: "Mã" }, { key: "name", label: "Tên" }, { key: "commissionType", label: "Loại" }, { key: "status", label: "Trạng thái", format: "status" },
      { key: "departmentName", label: "Phòng ban" }, { key: "jobLevelName", label: "Bậc" }, { key: "contractType", label: "Loại HĐ", format: "status" },
      { key: "targetRevenueMultiplier", label: "Định mức" }, { key: "defaultRate", label: "Tỷ lệ" }, { key: "effectiveFrom", label: "Hiệu lực", format: "date" },
    ],
    metrics: [
      { label: "Tổng chính sách", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang áp dụng", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
    ],
  },
  {
    key: "allowance-policies",
    title: "Chính sách phụ cấp",
    description: "Cấu hình phụ cấp/thu nhập theo nhóm, khu vực, loại thuế và ngày hiệu lực.",
    primaryAction: "Thêm chính sách phụ cấp",
    apiPath: "/api/allowance-policies",
    searchPlaceholder: "Tìm mã, tên, khu vực, loại thu nhập...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "130px" },
      { key: "name", label: "Tên chính sách", sortable: true, width: "230px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "incomeTypeName", label: "Loại thu nhập", width: "180px" },
      { key: "departmentName", label: "Phòng ban", width: "170px" },
      { key: "workArea", label: "Khu vực", width: "140px" },
      { key: "amount", label: "Số tiền", sortable: true, format: "money", width: "150px" },
      { key: "taxability", label: "Thuế", sortable: true, format: "status", width: "130px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "130px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: policyStatusOptions },
      { key: "incomeTypeId", label: "Loại thu nhập", type: "select", lookupKey: "incomeTypes" },
      { key: "departmentId", label: "Phòng ban", type: "select", lookupKey: "departments" },
      { key: "jobLevelId", label: "Bậc", type: "select", lookupKey: "jobLevels" },
      { key: "taxability", label: "Thuế", type: "select", options: taxabilityOptions },
    ],
    fields: [
      { key: "code", label: "Mã chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "name", label: "Tên chính sách", type: "text", required: true, section: "Thông tin" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: policyStatusOptions },
      { key: "incomeTypeId", label: "Loại thu nhập", type: "select", section: "Cấu hình", lookupKey: "incomeTypes" },
      { key: "amount", label: "Số tiền", type: "number", section: "Cấu hình" },
      { key: "taxability", label: "Tính thuế", type: "select", section: "Cấu hình", options: taxabilityOptions },
      { key: "departmentId", label: "Phòng ban", type: "select", section: "Phạm vi", lookupKey: "departments" },
      { key: "jobLevelId", label: "Bậc", type: "select", section: "Phạm vi", lookupKey: "jobLevels" },
      { key: "contractType", label: "Loại HĐ", type: "select", section: "Phạm vi", options: contractTypeOptions },
      { key: "workArea", label: "Khu vực", type: "text", section: "Phạm vi" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
    ],
    detailFields: [
      { key: "code", label: "Mã" }, { key: "name", label: "Tên" }, { key: "status", label: "Trạng thái", format: "status" },
      { key: "incomeTypeName", label: "Loại thu nhập" }, { key: "departmentName", label: "Phòng ban" }, { key: "jobLevelName", label: "Bậc" },
      { key: "workArea", label: "Khu vực" }, { key: "amount", label: "Số tiền", format: "money" }, { key: "taxability", label: "Thuế", format: "status" },
      { key: "effectiveFrom", label: "Hiệu lực", format: "date" },
    ],
    metrics: [
      { label: "Tổng chính sách", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang áp dụng", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Tổng tiền trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.amount ?? 0), 0)) },
    ],
  },
];
