import { formatCurrency, formatNumber } from "@/lib/formatters";
import type { ModuleConfig } from "@/features/shared/components/management/types";

const paymentMethodOptions = [
  { label: "Chuyển khoản", value: "bank_transfer" },
  { label: "Tiền mặt", value: "cash" },
  { label: "Cấn trừ", value: "offset" },
  { label: "Khác", value: "other" },
];

const debtEntryTypeOptions = [
  { label: "Số dư đầu kỳ", value: "opening_balance" },
  { label: "Ghi nợ đơn hàng", value: "order_debit" },
  { label: "Thu tiền", value: "payment_credit" },
  { label: "Điều chỉnh tăng", value: "adjustment_debit" },
  { label: "Điều chỉnh giảm", value: "adjustment_credit" },
  { label: "Xóa nợ", value: "write_off" },
];

const adjustmentDebtEntryTypeOptions = [
  { label: "Số dư đầu kỳ", value: "opening_balance" },
  { label: "Điều chỉnh tăng", value: "adjustment_debit" },
  { label: "Điều chỉnh giảm", value: "adjustment_credit" },
  { label: "Xóa nợ", value: "write_off" },
];

const settlementTypeOptions = [
  { label: "Phải trả", value: "payable" },
  { label: "Phải thu", value: "receivable" },
  { label: "Thu hộ", value: "collection_on_behalf" },
  { label: "Cấn trừ", value: "offset" },
];

const settlementStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Đã xác nhận", value: "confirmed" },
  { label: "Thanh toán một phần", value: "partially_paid" },
  { label: "Đã thanh toán", value: "paid" },
  { label: "Cấn trừ", value: "offset" },
  { label: "Đã hủy", value: "cancelled" },
];

export const financeModules: ModuleConfig[] = [
  {
    key: "payments",
    title: "Thanh toán",
    description: "Ghi nhận phiếu thu và phân bổ thủ công vào đơn hàng để giảm công nợ.",
    primaryAction: "Tạo phiếu thu",
    apiPath: "/api/payments",
    searchPlaceholder: "Tìm mã phiếu thu, khách hàng, tham chiếu...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "paymentNo", label: "Mã phiếu", sortable: true, width: "150px" },
      { key: "customerName", label: "Khách hàng", sortable: true, width: "260px" },
      { key: "paymentDate", label: "Ngày thu", sortable: true, format: "date", width: "130px" },
      { key: "method", label: "Phương thức", sortable: true, format: "status", width: "150px" },
      { key: "amount", label: "Số tiền", sortable: true, format: "money", width: "160px" },
      { key: "allocatedAmount", label: "Đã phân bổ", sortable: true, format: "money", width: "170px" },
      { key: "unallocatedAmount", label: "Chưa phân bổ", format: "money", width: "170px" },
      { key: "referenceNo", label: "Tham chiếu", width: "180px" },
    ],
    filters: [
      { key: "customerId", label: "Khách hàng", type: "select", lookupKey: "customers" },
      { key: "method", label: "Phương thức", type: "select", options: paymentMethodOptions },
      { key: "dateFrom", label: "Từ ngày", type: "date" },
      { key: "dateTo", label: "Đến ngày", type: "date" },
    ],
    fields: [
      { key: "paymentNo", label: "Mã phiếu thu", type: "text", required: true, section: "Thông tin phiếu" },
      { key: "customerId", label: "Khách hàng", type: "select", required: true, section: "Thông tin phiếu", lookupKey: "customers" },
      { key: "paymentDate", label: "Ngày thanh toán", type: "date", required: true, section: "Thông tin phiếu" },
      { key: "method", label: "Phương thức", type: "select", section: "Thông tin phiếu", options: paymentMethodOptions },
      { key: "amount", label: "Số tiền", type: "number", required: true, section: "Thông tin phiếu" },
      { key: "allocationOrderId", label: "Đơn hàng phân bổ", type: "select", section: "Phân bổ" , lookupKey: "issuedOrders" },
      { key: "allocatedAmount", label: "Số tiền phân bổ", type: "number", section: "Phân bổ" },
      { key: "referenceNo", label: "Số tham chiếu", type: "text", section: "Thông tin phiếu" },
      { key: "description", label: "Diễn giải", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "paymentNo", label: "Mã phiếu" },
      { key: "customerName", label: "Khách hàng" },
      { key: "paymentDate", label: "Ngày thu", format: "date" },
      { key: "method", label: "Phương thức", format: "status" },
      { key: "amount", label: "Số tiền", format: "money" },
      { key: "allocatedAmount", label: "Đã phân bổ", format: "money" },
      { key: "unallocatedAmount", label: "Chưa phân bổ", format: "money" },
      { key: "referenceNo", label: "Tham chiếu" },
      { key: "description", label: "Diễn giải" },
    ],
    metrics: [
      { label: "Tổng phiếu", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Số tiền trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.amount ?? 0), 0)) },
      { label: "Đã phân bổ trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.allocatedAmount ?? 0), 0)) },
    ],
  },
  {
    key: "debt-entries",
    title: "Sổ công nợ",
    description: "Theo dõi chi tiết phát sinh tăng/giảm công nợ và tạo điều chỉnh có lý do.",
    primaryAction: "Tạo điều chỉnh",
    apiPath: "/api/debt-entries",
    searchPlaceholder: "Tìm khách hàng, đơn hàng, phiếu thu, diễn giải...",
    defaultSortBy: "entryDate",
    columns: [
      { key: "entryDate", label: "Ngày", sortable: true, format: "date", width: "130px" },
      { key: "customerName", label: "Khách hàng", sortable: true, width: "260px" },
      { key: "orderNo", label: "Đơn hàng", sortable: true, width: "150px" },
      { key: "paymentNo", label: "Phiếu thu", sortable: true, width: "150px" },
      { key: "entryType", label: "Loại", sortable: true, format: "status", width: "170px" },
      { key: "debitAmount", label: "Tăng", sortable: true, format: "money", width: "150px" },
      { key: "creditAmount", label: "Giảm", sortable: true, format: "money", width: "150px" },
      { key: "balanceAfterEntry", label: "Số dư", sortable: true, format: "money", width: "160px" },
      { key: "isLocked", label: "Khóa", format: "boolean", width: "110px" },
    ],
    filters: [
      { key: "customerId", label: "Khách hàng", type: "select", lookupKey: "customers" },
      { key: "entryType", label: "Loại dòng", type: "select", options: debtEntryTypeOptions },
    ],
    fields: [
      { key: "customerId", label: "Khách hàng", type: "select", required: true, section: "Liên kết", lookupKey: "customers" },
      { key: "orderId", label: "Đơn hàng", type: "select", section: "Liên kết", lookupKey: "orders" },
      { key: "paymentId", label: "Phiếu thu", type: "select", section: "Liên kết", lookupKey: "payments" },
      { key: "entryDate", label: "Ngày ghi nhận", type: "date", required: true, section: "Điều chỉnh" },
      { key: "entryType", label: "Loại điều chỉnh", type: "select", section: "Điều chỉnh", options: adjustmentDebtEntryTypeOptions },
      { key: "debitAmount", label: "Số tiền tăng", type: "number", section: "Điều chỉnh" },
      { key: "creditAmount", label: "Số tiền giảm", type: "number", section: "Điều chỉnh" },
      { key: "description", label: "Lý do", type: "textarea", required: true, section: "Điều chỉnh" },
    ],
    detailFields: [
      { key: "entryDate", label: "Ngày", format: "date" },
      { key: "customerName", label: "Khách hàng" },
      { key: "orderNo", label: "Đơn hàng" },
      { key: "paymentNo", label: "Phiếu thu" },
      { key: "entryType", label: "Loại", format: "status" },
      { key: "debitAmount", label: "Tăng", format: "money" },
      { key: "creditAmount", label: "Giảm", format: "money" },
      { key: "balanceAfterEntry", label: "Số dư", format: "money" },
      { key: "isLocked", label: "Đã khóa", format: "boolean" },
      { key: "description", label: "Diễn giải" },
    ],
    metrics: [
      { label: "Tổng dòng", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Tăng trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.debitAmount ?? 0), 0)) },
      { label: "Giảm trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.creditAmount ?? 0), 0)) },
    ],
  },
  {
    key: "debt-summary",
    title: "Tổng hợp công nợ",
    description: "Báo cáo nợ đầu kỳ, phát sinh tăng/giảm, nợ cuối kỳ và quá hạn theo khách hàng.",
    primaryAction: "Không dùng",
    apiPath: "/api/debt-summary",
    searchPlaceholder: "Tìm khách hàng...",
    defaultSortBy: "customerName",
    canCreate: false,
    canEdit: false,
    canDelete: false,
    columns: [
      { key: "customerCode", label: "Mã KH", sortable: true, width: "130px" },
      { key: "customerName", label: "Khách hàng", sortable: true, width: "280px" },
      { key: "openingBalance", label: "Nợ đầu kỳ", format: "money", width: "170px" },
      { key: "debitAmount", label: "Phát sinh tăng", format: "money", width: "170px" },
      { key: "creditAmount", label: "Phát sinh giảm", format: "money", width: "170px" },
      { key: "closingBalance", label: "Nợ cuối kỳ", sortable: true, format: "money", width: "170px" },
      { key: "overdueAmount", label: "Quá hạn", sortable: true, format: "money", width: "170px" },
    ],
    filters: [
      { key: "customerId", label: "Khách hàng", type: "select", lookupKey: "customers" },
      { key: "periodStart", label: "Từ ngày", type: "date" },
      { key: "periodEnd", label: "Đến ngày", type: "date" },
    ],
    fields: [],
    detailFields: [
      { key: "customerCode", label: "Mã KH" },
      { key: "customerName", label: "Khách hàng" },
      { key: "openingBalance", label: "Nợ đầu kỳ", format: "money" },
      { key: "debitAmount", label: "Phát sinh tăng", format: "money" },
      { key: "creditAmount", label: "Phát sinh giảm", format: "money" },
      { key: "closingBalance", label: "Nợ cuối kỳ", format: "money" },
      { key: "overdueAmount", label: "Quá hạn", format: "money" },
    ],
    metrics: [
      { label: "Số khách hàng", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Nợ cuối kỳ trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.closingBalance ?? 0), 0)) },
      { label: "Quá hạn trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.overdueAmount ?? 0), 0)) },
    ],
  },
  {
    key: "debt-closings",
    title: "Chốt kỳ công nợ",
    description: "Tạo snapshot công nợ theo kỳ và khóa các dòng phát sinh trong kỳ.",
    primaryAction: "Chốt kỳ",
    apiPath: "/api/debt-closings",
    searchPlaceholder: "Tìm khách hàng đã chốt...",
    defaultSortBy: "createdAt",
    canEdit: false,
    canDelete: false,
    columns: [
      { key: "customerName", label: "Khách hàng", sortable: true, width: "260px" },
      { key: "periodStart", label: "Từ ngày", sortable: true, format: "date", width: "140px" },
      { key: "periodEnd", label: "Đến ngày", sortable: true, format: "date", width: "140px" },
      { key: "openingBalance", label: "Đầu kỳ", format: "money", width: "160px" },
      { key: "debitAmount", label: "Tăng", format: "money", width: "160px" },
      { key: "creditAmount", label: "Giảm", format: "money", width: "160px" },
      { key: "closingBalance", label: "Cuối kỳ", sortable: true, format: "money", width: "160px" },
      { key: "lockedAt", label: "Khóa lúc", sortable: true, format: "date", width: "140px" },
    ],
    filters: [{ key: "customerId", label: "Khách hàng", type: "select", lookupKey: "customers" }],
    fields: [
      { key: "customerId", label: "Khách hàng", type: "select", section: "Kỳ chốt", lookupKey: "customers" },
      { key: "periodStart", label: "Từ ngày", type: "date", required: true, section: "Kỳ chốt" },
      { key: "periodEnd", label: "Đến ngày", type: "date", required: true, section: "Kỳ chốt" },
    ],
    detailFields: [
      { key: "customerName", label: "Khách hàng" },
      { key: "periodStart", label: "Từ ngày", format: "date" },
      { key: "periodEnd", label: "Đến ngày", format: "date" },
      { key: "openingBalance", label: "Đầu kỳ", format: "money" },
      { key: "debitAmount", label: "Tăng", format: "money" },
      { key: "creditAmount", label: "Giảm", format: "money" },
      { key: "closingBalance", label: "Cuối kỳ", format: "money" },
      { key: "lockedAt", label: "Đã khóa", format: "date" },
    ],
    metrics: [
      { label: "Kỳ đã chốt", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Nợ cuối kỳ trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.closingBalance ?? 0), 0)) },
      { label: "Dòng trên trang", getValue: (records) => formatNumber(records.length) },
    ],
  },
  {
    key: "partner-settlements",
    title: "Đối soát TOPA",
    description: "Quản lý khoản phải trả, phải thu, thu hộ hoặc cấn trừ với TOPA/đối tác.",
    primaryAction: "Tạo đối soát",
    apiPath: "/api/partner-settlements",
    searchPlaceholder: "Tìm mã đối soát, đối tác, đơn hàng...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "settlementNo", label: "Mã đối soát", sortable: true, width: "160px" },
      { key: "partnerName", label: "Đối tác", sortable: true, width: "220px" },
      { key: "orderNo", label: "Đơn hàng", sortable: true, width: "150px" },
      { key: "settlementType", label: "Loại", sortable: true, format: "status", width: "150px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "160px" },
      { key: "settlementDate", label: "Ngày", sortable: true, format: "date", width: "130px" },
      { key: "amount", label: "Số tiền", sortable: true, format: "money", width: "160px" },
      { key: "paidAmount", label: "Đã trả/thu", sortable: true, format: "money", width: "160px" },
      { key: "remainingAmount", label: "Còn lại", format: "money", width: "160px" },
    ],
    filters: [
      { key: "partnerId", label: "Đối tác", type: "select", lookupKey: "partners" },
      { key: "status", label: "Trạng thái", type: "select", options: settlementStatusOptions },
      { key: "settlementType", label: "Loại", type: "select", options: settlementTypeOptions },
    ],
    fields: [
      { key: "settlementNo", label: "Mã đối soát", type: "text", required: true, section: "Thông tin" },
      { key: "partnerId", label: "Đối tác", type: "select", required: true, section: "Thông tin", lookupKey: "partners" },
      { key: "orderId", label: "Đơn hàng", type: "select", section: "Thông tin", lookupKey: "orders" },
      { key: "settlementType", label: "Loại đối soát", type: "select", section: "Thông tin", options: settlementTypeOptions },
      { key: "status", label: "Trạng thái", type: "select", section: "Thông tin", options: settlementStatusOptions },
      { key: "settlementDate", label: "Ngày đối soát", type: "date", required: true, section: "Thời hạn" },
      { key: "dueDate", label: "Ngày đến hạn", type: "date", section: "Thời hạn" },
      { key: "amount", label: "Số tiền", type: "number", section: "Tài chính" },
      { key: "paidAmount", label: "Đã trả/thu", type: "number", section: "Tài chính" },
      { key: "description", label: "Diễn giải", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "settlementNo", label: "Mã đối soát" },
      { key: "partnerName", label: "Đối tác" },
      { key: "orderNo", label: "Đơn hàng" },
      { key: "settlementType", label: "Loại", format: "status" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "settlementDate", label: "Ngày", format: "date" },
      { key: "dueDate", label: "Đến hạn", format: "date" },
      { key: "amount", label: "Số tiền", format: "money" },
      { key: "paidAmount", label: "Đã trả/thu", format: "money" },
      { key: "remainingAmount", label: "Còn lại", format: "money" },
      { key: "description", label: "Diễn giải" },
    ],
    metrics: [
      { label: "Tổng khoản", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Giá trị trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.amount ?? 0), 0)) },
      { label: "Còn lại trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.remainingAmount ?? 0), 0)) },
    ],
  },
  {
    key: "partner-settlement-payments",
    title: "Thanh toán đối tác",
    description: "Ghi nhận các khoản thanh toán/cấn trừ cho từng khoản đối soát đối tác.",
    primaryAction: "Tạo thanh toán đối tác",
    apiPath: "/api/partner-settlement-payments",
    searchPlaceholder: "Tìm mã đối soát, đối tác, tham chiếu...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "settlementNo", label: "Mã đối soát", sortable: true, width: "170px" },
      { key: "partnerName", label: "Đối tác", sortable: true, width: "220px" },
      { key: "paymentDate", label: "Ngày", sortable: true, format: "date", width: "130px" },
      { key: "method", label: "Phương thức", sortable: true, format: "status", width: "150px" },
      { key: "amount", label: "Số tiền", sortable: true, format: "money", width: "160px" },
      { key: "referenceNo", label: "Tham chiếu", width: "180px" },
      { key: "description", label: "Diễn giải", width: "280px" },
    ],
    filters: [
      { key: "partnerSettlementId", label: "Đối soát", type: "select", lookupKey: "partnerSettlements" },
      { key: "method", label: "Phương thức", type: "select", options: paymentMethodOptions },
    ],
    fields: [
      { key: "partnerSettlementId", label: "Khoản đối soát", type: "select", required: true, section: "Liên kết", lookupKey: "partnerSettlements" },
      { key: "paymentDate", label: "Ngày thanh toán", type: "date", required: true, section: "Thanh toán" },
      { key: "method", label: "Phương thức", type: "select", section: "Thanh toán", options: paymentMethodOptions },
      { key: "amount", label: "Số tiền", type: "number", required: true, section: "Thanh toán" },
      { key: "referenceNo", label: "Số tham chiếu", type: "text", section: "Thanh toán" },
      { key: "description", label: "Diễn giải", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "settlementNo", label: "Mã đối soát" },
      { key: "partnerName", label: "Đối tác" },
      { key: "paymentDate", label: "Ngày", format: "date" },
      { key: "method", label: "Phương thức", format: "status" },
      { key: "amount", label: "Số tiền", format: "money" },
      { key: "referenceNo", label: "Tham chiếu" },
      { key: "description", label: "Diễn giải" },
    ],
    metrics: [
      { label: "Tổng giao dịch", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Số tiền trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.amount ?? 0), 0)) },
      { label: "Dòng trên trang", getValue: (records) => formatNumber(records.length) },
    ],
  },
];
