import { formatCurrency, formatNumber } from "@/lib/formatters";
import type { HrModuleConfig } from "./types";

const employeeStatusOptions = [
  { label: "Đang làm", value: "active" },
  { label: "Thử việc", value: "probation" },
  { label: "Tạm ngưng", value: "inactive" },
  { label: "Đã nghỉ", value: "terminated" },
];

const contractTypeOptions = [
  { label: "Full-time", value: "full_time" },
  { label: "Part-time", value: "part_time" },
  { label: "Thử việc", value: "probation" },
  { label: "Cộng tác viên", value: "contractor" },
  { label: "Khác", value: "other" },
];

const salaryPaymentTypeOptions = [
  { label: "Gross", value: "gross" },
  { label: "Net", value: "net" },
];

const yesNoOptions = [
  { label: "Có", value: "true" },
  { label: "Không", value: "false" },
];

const leaveRequestStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Chờ duyệt", value: "pending" },
  { label: "Đã duyệt", value: "approved" },
  { label: "Từ chối", value: "rejected" },
  { label: "Đã hủy", value: "cancelled" },
];

const taxabilityOptions = [
  { label: "Chịu thuế", value: "taxable" },
  { label: "Miễn thuế", value: "non_taxable" },
];

export const hrModules: HrModuleConfig[] = [
  {
    key: "departments",
    title: "Phòng ban",
    description: "Quản lý phòng ban, phòng cha và trưởng phòng để làm nền cho phân quyền, KPI và bảng lương.",
    primaryAction: "Thêm phòng ban",
    apiPath: "/api/departments",
    searchPlaceholder: "Tìm theo mã hoặc tên phòng ban...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã phòng", sortable: true, width: "140px" },
      { key: "name", label: "Tên phòng ban", sortable: true, width: "260px" },
      { key: "parentDepartmentName", label: "Phòng cha", sortable: true, width: "220px" },
      { key: "managerEmployeeName", label: "Trưởng phòng", sortable: true, width: "220px" },
      { key: "description", label: "Mô tả", width: "360px" },
    ],
    filters: [],
    fields: [
      { key: "code", label: "Mã phòng ban", type: "text", required: true, section: "Thông tin phòng ban" },
      { key: "name", label: "Tên phòng ban", type: "text", required: true, section: "Thông tin phòng ban" },
      { key: "parentDepartmentId", label: "Phòng cha", type: "select", section: "Cấu trúc", lookupKey: "departments" },
      { key: "managerEmployeeId", label: "Trưởng phòng", type: "select", section: "Cấu trúc", lookupKey: "employees" },
      { key: "description", label: "Mô tả", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã phòng ban" },
      { key: "name", label: "Tên phòng ban" },
      { key: "parentDepartmentName", label: "Phòng cha" },
      { key: "managerEmployeeName", label: "Trưởng phòng" },
      { key: "description", label: "Mô tả" },
    ],
    metrics: [
      { label: "Tổng phòng ban", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Có trưởng phòng", getValue: (records) => formatNumber(records.filter((item) => item.managerEmployeeId).length) },
    ],
  },
  {
    key: "job-levels",
    title: "Bậc chức danh",
    description: "Quản lý bậc, chức danh và thứ tự cấp bậc dùng cho cơ cấu nhân sự và chính sách lương.",
    primaryAction: "Thêm bậc",
    apiPath: "/api/job-levels",
    searchPlaceholder: "Tìm theo mã hoặc tên bậc...",
    defaultSortBy: "rankOrder",
    columns: [
      { key: "code", label: "Mã bậc", sortable: true, width: "140px" },
      { key: "name", label: "Tên bậc/chức danh", sortable: true, width: "280px" },
      { key: "rankOrder", label: "Thứ tự", sortable: true, width: "140px" },
      { key: "description", label: "Mô tả", width: "420px" },
    ],
    filters: [],
    fields: [
      { key: "code", label: "Mã bậc", type: "text", required: true, section: "Thông tin bậc" },
      { key: "name", label: "Tên bậc/chức danh", type: "text", required: true, section: "Thông tin bậc" },
      { key: "rankOrder", label: "Thứ tự cấp bậc", type: "number", section: "Cấu hình" },
      { key: "description", label: "Mô tả", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã bậc" },
      { key: "name", label: "Tên bậc/chức danh" },
      { key: "rankOrder", label: "Thứ tự" },
      { key: "description", label: "Mô tả" },
    ],
    metrics: [
      { label: "Tổng bậc", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Thứ tự cao nhất", getValue: (records) => formatNumber(Math.max(0, ...records.map((item) => Number(item.rankOrder ?? 0)))) },
    ],
  },
  {
    key: "employees",
    title: "Nhân viên",
    description: "Quản lý hồ sơ nhân viên, phòng ban, bậc chức danh và hợp đồng hiện hành để làm dữ liệu gốc.",
    primaryAction: "Thêm nhân viên",
    apiPath: "/api/employees",
    searchPlaceholder: "Tìm theo mã NV, họ tên, email, SĐT...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "employeeCode", label: "Mã NV", sortable: true, width: "120px" },
      { key: "fullName", label: "Họ tên", sortable: true, width: "220px" },
      { key: "departmentName", label: "Phòng ban", sortable: true, width: "180px" },
      { key: "jobLevelName", label: "Bậc", sortable: true, width: "180px" },
      { key: "contractType", label: "Loại HĐ", sortable: true, format: "status", width: "140px" },
      { key: "salaryPaymentType", label: "Gross/Net", sortable: true, format: "status", width: "120px" },
      { key: "baseSalary", label: "Lương cơ bản", sortable: true, format: "money", width: "170px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "hireDate", label: "Ngày vào", sortable: true, format: "date", width: "140px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: employeeStatusOptions, placeholder: "Tất cả trạng thái" },
      { key: "departmentId", label: "Phòng ban", type: "select", options: [], lookupKey: "departments", placeholder: "Tất cả phòng ban" },
      { key: "jobLevelId", label: "Bậc", type: "select", options: [], lookupKey: "jobLevels", placeholder: "Tất cả bậc" },
      { key: "contractType", label: "Loại HĐ", type: "select", options: contractTypeOptions, placeholder: "Tất cả loại HĐ" },
      { key: "salaryPaymentType", label: "Gross/Net", type: "select", options: salaryPaymentTypeOptions, placeholder: "Tất cả hình thức" },
    ],
    fields: [
      { key: "employeeCode", label: "Mã nhân viên", type: "text", required: true, section: "Thông tin nhân viên" },
      { key: "fullName", label: "Họ và tên", type: "text", required: true, section: "Thông tin nhân viên" },
      { key: "shortName", label: "Tên gọi tắt", type: "text", section: "Thông tin nhân viên" },
      { key: "departmentId", label: "Phòng ban", type: "select", section: "Tổ chức", lookupKey: "departments" },
      { key: "jobLevelId", label: "Bậc/chức danh", type: "select", section: "Tổ chức", lookupKey: "jobLevels" },
      { key: "status", label: "Trạng thái", type: "select", section: "Tổ chức", options: employeeStatusOptions },
      { key: "hireDate", label: "Ngày vào làm", type: "date", section: "Tổ chức" },
      { key: "terminationDate", label: "Ngày nghỉ", type: "date", section: "Tổ chức" },
      { key: "workEmail", label: "Email công việc", type: "text", section: "Liên hệ" },
      { key: "personalEmail", label: "Email cá nhân", type: "text", section: "Liên hệ" },
      { key: "phone", label: "Số điện thoại", type: "text", section: "Liên hệ" },
      { key: "contractType", label: "Loại hợp đồng", type: "select", required: true, section: "Hợp đồng hiện hành", options: contractTypeOptions },
      { key: "salaryPaymentType", label: "Hình thức nhận lương", type: "select", required: true, section: "Hợp đồng hiện hành", options: salaryPaymentTypeOptions },
      { key: "baseSalary", label: "Lương cơ bản", type: "number", section: "Hợp đồng hiện hành" },
      { key: "standardWorkdays", label: "Ngày công chuẩn", type: "number", section: "Hợp đồng hiện hành" },
      { key: "contractEffectiveFrom", label: "Hiệu lực từ", type: "date", section: "Hợp đồng hiện hành" },
      { key: "contractEffectiveTo", label: "Hiệu lực đến", type: "date", section: "Hợp đồng hiện hành" },
      { key: "bankName", label: "Ngân hàng", type: "text", section: "Thanh toán" },
      { key: "bankAccountNumber", label: "Số tài khoản", type: "text", section: "Thanh toán" },
      { key: "bankAccountName", label: "Tên tài khoản", type: "text", section: "Thanh toán" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "employeeCode", label: "Mã nhân viên" },
      { key: "fullName", label: "Họ và tên" },
      { key: "shortName", label: "Tên gọi tắt" },
      { key: "departmentName", label: "Phòng ban" },
      { key: "jobLevelName", label: "Bậc/chức danh" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "hireDate", label: "Ngày vào làm", format: "date" },
      { key: "terminationDate", label: "Ngày nghỉ", format: "date" },
      { key: "workEmail", label: "Email công việc" },
      { key: "personalEmail", label: "Email cá nhân" },
      { key: "phone", label: "Số điện thoại" },
      { key: "contractType", label: "Loại hợp đồng", format: "status" },
      { key: "salaryPaymentType", label: "Hình thức lương", format: "status" },
      { key: "baseSalary", label: "Lương cơ bản", format: "money" },
      { key: "standardWorkdays", label: "Ngày công chuẩn" },
      { key: "contractEffectiveFrom", label: "Hiệu lực từ", format: "date" },
      { key: "contractEffectiveTo", label: "Hiệu lực đến", format: "date" },
      { key: "bankName", label: "Ngân hàng" },
      { key: "bankAccountNumber", label: "Số tài khoản" },
      { key: "bankAccountName", label: "Tên tài khoản" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng nhân viên", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang làm trên trang", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Quỹ lương trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.baseSalary ?? 0), 0)) },
    ],
  },
  {
    key: "employee-dependents",
    title: "Người phụ thuộc",
    description: "Quản lý người phụ thuộc theo từng nhân viên và giai đoạn hiệu lực để phục vụ giảm trừ thuế.",
    primaryAction: "Thêm người phụ thuộc",
    apiPath: "/api/employee-dependents",
    searchPlaceholder: "Tìm theo nhân viên, người phụ thuộc, quan hệ, mã thuế...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "220px" },
      { key: "fullName", label: "Người phụ thuộc", sortable: true, width: "240px" },
      { key: "relationship", label: "Quan hệ", sortable: true, width: "160px" },
      { key: "taxDependentCode", label: "Mã NPT", width: "180px" },
      { key: "effectiveFrom", label: "Hiệu lực từ", sortable: true, format: "date", width: "140px" },
      { key: "effectiveTo", label: "Hiệu lực đến", format: "date", width: "140px" },
    ],
    filters: [
      { key: "employeeId", label: "Nhân viên", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân viên" },
    ],
    fields: [
      { key: "employeeId", label: "Nhân viên", type: "select", required: true, section: "Liên kết", lookupKey: "employees" },
      { key: "fullName", label: "Họ tên người phụ thuộc", type: "text", required: true, section: "Thông tin người phụ thuộc" },
      { key: "relationship", label: "Quan hệ", type: "text", section: "Thông tin người phụ thuộc" },
      { key: "taxDependentCode", label: "Mã người phụ thuộc", type: "text", section: "Thông tin người phụ thuộc" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
    ],
    detailFields: [
      { key: "employeeName", label: "Nhân viên" },
      { key: "fullName", label: "Người phụ thuộc" },
      { key: "relationship", label: "Quan hệ" },
      { key: "taxDependentCode", label: "Mã người phụ thuộc" },
      { key: "effectiveFrom", label: "Hiệu lực từ", format: "date" },
      { key: "effectiveTo", label: "Hiệu lực đến", format: "date" },
    ],
    metrics: [
      { label: "Tổng người phụ thuộc", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Đang hiệu lực", getValue: (records) => formatNumber(records.filter((item) => !item.effectiveTo).length) },
    ],
  },
  {
    key: "payroll-settings",
    title: "Cấu hình lương cá nhân",
    description: "Quản lý cấu hình tính lương, bảo hiểm và điều kiện nhận hoa hồng theo từng nhân viên.",
    primaryAction: "Thêm cấu hình lương",
    apiPath: "/api/payroll-settings",
    searchPlaceholder: "Tìm theo mã hoặc tên nhân viên...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "230px" },
      { key: "salaryPaymentType", label: "Gross/Net", sortable: true, format: "status", width: "120px" },
      { key: "participatesInsurance", label: "BH", sortable: true, format: "boolean", width: "100px" },
      { key: "eligibleForCommission", label: "Hoa hồng", format: "boolean", width: "130px" },
      { key: "eligibleForExceededRevenueCommission", label: "Vượt DS", format: "boolean", width: "120px" },
      { key: "eligibleForOneTimeCustomerCommission", label: "Khách 1 lần", format: "boolean", width: "130px" },
      { key: "eligibleForNewCustomerCommission", label: "Khách mới", format: "boolean", width: "120px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "140px" },
      { key: "effectiveTo", label: "Kết thúc", format: "date", width: "140px" },
    ],
    filters: [
      { key: "employeeId", label: "Nhân viên", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân viên" },
      { key: "salaryPaymentType", label: "Gross/Net", type: "select", options: salaryPaymentTypeOptions, placeholder: "Tất cả hình thức" },
      { key: "participatesInsurance", label: "Tham gia BH", type: "select", options: yesNoOptions, placeholder: "Tất cả" },
    ],
    fields: [
      { key: "employeeId", label: "Nhân viên", type: "select", required: true, section: "Liên kết", lookupKey: "employees" },
      { key: "salaryPaymentType", label: "Hình thức lương", type: "select", section: "Cấu hình", options: salaryPaymentTypeOptions },
      { key: "participatesInsurance", label: "Tham gia bảo hiểm", type: "checkbox", section: "Bảo hiểm" },
      { key: "eligibleForCommission", label: "Được nhận hoa hồng", type: "checkbox", section: "Hoa hồng" },
      { key: "eligibleForExceededRevenueCommission", label: "Hoa hồng vượt doanh số", type: "checkbox", section: "Hoa hồng" },
      { key: "eligibleForOneTimeCustomerCommission", label: "Hoa hồng khách 1 lần", type: "checkbox", section: "Hoa hồng" },
      { key: "eligibleForNewCustomerCommission", label: "Hoa hồng khách mới", type: "checkbox", section: "Hoa hồng" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
    ],
    detailFields: [
      { key: "employeeName", label: "Nhân viên" },
      { key: "salaryPaymentType", label: "Hình thức lương", format: "status" },
      { key: "participatesInsurance", label: "Tham gia bảo hiểm", format: "boolean" },
      { key: "eligibleForCommission", label: "Được nhận hoa hồng", format: "boolean" },
      { key: "eligibleForExceededRevenueCommission", label: "Hoa hồng vượt doanh số", format: "boolean" },
      { key: "eligibleForOneTimeCustomerCommission", label: "Hoa hồng khách 1 lần", format: "boolean" },
      { key: "eligibleForNewCustomerCommission", label: "Hoa hồng khách mới", format: "boolean" },
      { key: "effectiveFrom", label: "Hiệu lực từ", format: "date" },
      { key: "effectiveTo", label: "Hiệu lực đến", format: "date" },
    ],
    metrics: [
      { label: "Tổng cấu hình", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Tham gia BH", getValue: (records) => formatNumber(records.filter((item) => item.participatesInsurance).length) },
      { label: "Nhận hoa hồng", getValue: (records) => formatNumber(records.filter((item) => item.eligibleForCommission).length) },
    ],
  },
  {
    key: "leave-types",
    title: "Loại phép",
    description: "Quản lý danh mục loại phép, có hưởng lương hay không và hạn mức năm.",
    primaryAction: "Thêm loại phép",
    apiPath: "/api/leave-types",
    searchPlaceholder: "Tìm theo mã hoặc tên loại phép...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "130px" },
      { key: "name", label: "Tên loại phép", sortable: true, width: "280px" },
      { key: "isPaid", label: "Có lương", sortable: true, format: "boolean", width: "130px" },
      { key: "annualQuotaDays", label: "Hạn mức/năm", sortable: true, width: "150px" },
    ],
    filters: [
      { key: "isPaid", label: "Có hưởng lương", type: "select", options: yesNoOptions, placeholder: "Tất cả" },
    ],
    fields: [
      { key: "code", label: "Mã loại phép", type: "text", required: true, section: "Thông tin loại phép" },
      { key: "name", label: "Tên loại phép", type: "text", required: true, section: "Thông tin loại phép" },
      { key: "annualQuotaDays", label: "Hạn mức năm", type: "number", section: "Cấu hình" },
      { key: "isPaid", label: "Có hưởng lương", type: "checkbox", section: "Cấu hình" },
    ],
    detailFields: [
      { key: "code", label: "Mã loại phép" },
      { key: "name", label: "Tên loại phép" },
      { key: "isPaid", label: "Có hưởng lương", format: "boolean" },
      { key: "annualQuotaDays", label: "Hạn mức năm" },
    ],
    metrics: [
      { label: "Tổng loại phép", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Có lương", getValue: (records) => formatNumber(records.filter((item) => item.isPaid).length) },
    ],
  },
  {
    key: "leave-requests",
    title: "Đơn nghỉ phép",
    description: "Quản lý đơn nghỉ phép của nhân viên, trạng thái duyệt, số ngày và lý do.",
    primaryAction: "Thêm đơn nghỉ",
    apiPath: "/api/leave-requests",
    searchPlaceholder: "Tìm theo nhân viên, loại phép hoặc lý do...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "220px" },
      { key: "leaveTypeName", label: "Loại phép", sortable: true, width: "180px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "startDate", label: "Từ ngày", sortable: true, format: "date", width: "130px" },
      { key: "endDate", label: "Đến ngày", sortable: true, format: "date", width: "130px" },
      { key: "totalDays", label: "Số ngày", sortable: true, width: "110px" },
      { key: "approvedByName", label: "Người duyệt", width: "180px" },
    ],
    filters: [
      { key: "employeeId", label: "Nhân viên", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân viên" },
      { key: "leaveTypeId", label: "Loại phép", type: "select", options: [], lookupKey: "leaveTypes", placeholder: "Tất cả loại phép" },
      { key: "status", label: "Trạng thái", type: "select", options: leaveRequestStatusOptions, placeholder: "Tất cả trạng thái" },
    ],
    fields: [
      { key: "employeeId", label: "Nhân viên", type: "select", required: true, section: "Thông tin nghỉ phép", lookupKey: "employees" },
      { key: "leaveTypeId", label: "Loại phép", type: "select", required: true, section: "Thông tin nghỉ phép", lookupKey: "leaveTypes" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: leaveRequestStatusOptions },
      { key: "startDate", label: "Từ ngày", type: "date", required: true, section: "Thời gian" },
      { key: "endDate", label: "Đến ngày", type: "date", required: true, section: "Thời gian" },
      { key: "totalDays", label: "Tổng số ngày", type: "number", required: true, section: "Thời gian" },
      { key: "reason", label: "Lý do", type: "textarea", section: "Ghi chú" },
      { key: "approvedBy", label: "Người duyệt", type: "select", section: "Duyệt phép", lookupKey: "employees" },
      { key: "approvedAt", label: "Ngày duyệt", type: "date", section: "Duyệt phép" },
      { key: "rejectedReason", label: "Lý do từ chối", type: "textarea", section: "Duyệt phép" },
    ],
    detailFields: [
      { key: "employeeName", label: "Nhân viên" },
      { key: "leaveTypeName", label: "Loại phép" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "startDate", label: "Từ ngày", format: "date" },
      { key: "endDate", label: "Đến ngày", format: "date" },
      { key: "totalDays", label: "Tổng số ngày" },
      { key: "reason", label: "Lý do" },
      { key: "approvedByName", label: "Người duyệt" },
      { key: "approvedAt", label: "Ngày duyệt", format: "date" },
      { key: "rejectedReason", label: "Lý do từ chối" },
    ],
    metrics: [
      { label: "Tổng đơn nghỉ", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Chờ duyệt", getValue: (records) => formatNumber(records.filter((item) => item.status === "pending").length) },
      { label: "Đã duyệt", getValue: (records) => formatNumber(records.filter((item) => item.status === "approved").length) },
    ],
  },
  {
    key: "leave-balances",
    title: "Số dư phép",
    description: "Quản lý tổng ngày phép theo nhân viên, loại phép và năm để phục vụ báo cáo cá nhân/team.",
    primaryAction: "Thêm số dư phép",
    apiPath: "/api/leave-balances",
    searchPlaceholder: "Tìm theo nhân viên hoặc loại phép...",
    defaultSortBy: "year",
    columns: [
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "220px" },
      { key: "leaveTypeName", label: "Loại phép", sortable: true, width: "180px" },
      { key: "year", label: "Năm", sortable: true, width: "100px" },
      { key: "openingDays", label: "Đầu kỳ", width: "110px" },
      { key: "earnedDays", label: "Phát sinh", width: "110px" },
      { key: "usedDays", label: "Đã dùng", width: "110px" },
      { key: "adjustedDays", label: "Điều chỉnh", width: "120px" },
      { key: "closingDays", label: "Cuối kỳ", sortable: true, width: "110px" },
    ],
    filters: [
      { key: "employeeId", label: "Nhân viên", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân viên" },
      { key: "leaveTypeId", label: "Loại phép", type: "select", options: [], lookupKey: "leaveTypes", placeholder: "Tất cả loại phép" },
    ],
    fields: [
      { key: "employeeId", label: "Nhân viên", type: "select", required: true, section: "Liên kết", lookupKey: "employees" },
      { key: "leaveTypeId", label: "Loại phép", type: "select", required: true, section: "Liên kết", lookupKey: "leaveTypes" },
      { key: "year", label: "Năm", type: "number", required: true, section: "Kỳ phép" },
      { key: "openingDays", label: "Ngày đầu kỳ", type: "number", section: "Số dư" },
      { key: "earnedDays", label: "Ngày phát sinh", type: "number", section: "Số dư" },
      { key: "usedDays", label: "Ngày đã dùng", type: "number", section: "Số dư" },
      { key: "adjustedDays", label: "Ngày điều chỉnh", type: "number", section: "Số dư" },
      { key: "closingDays", label: "Ngày cuối kỳ", type: "number", section: "Số dư" },
    ],
    detailFields: [
      { key: "employeeName", label: "Nhân viên" },
      { key: "leaveTypeName", label: "Loại phép" },
      { key: "year", label: "Năm" },
      { key: "openingDays", label: "Ngày đầu kỳ" },
      { key: "earnedDays", label: "Ngày phát sinh" },
      { key: "usedDays", label: "Ngày đã dùng" },
      { key: "adjustedDays", label: "Ngày điều chỉnh" },
      { key: "closingDays", label: "Ngày cuối kỳ" },
    ],
    metrics: [
      { label: "Tổng dòng số dư", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Tổng còn lại trên trang", getValue: (records) => formatNumber(records.reduce((sum, item) => sum + Number(item.closingDays ?? 0), 0)) },
    ],
  },
  {
    key: "company-holidays",
    title: "Lịch nghỉ công ty",
    description: "Quản lý lịch nghỉ toàn công ty để nhân viên và trưởng phòng cùng theo dõi.",
    primaryAction: "Thêm ngày nghỉ",
    apiPath: "/api/company-holidays",
    searchPlaceholder: "Tìm theo tên ngày nghỉ...",
    defaultSortBy: "holidayDate",
    columns: [
      { key: "holidayDate", label: "Ngày nghỉ", sortable: true, format: "date", width: "150px" },
      { key: "name", label: "Tên ngày nghỉ", sortable: true, width: "300px" },
      { key: "isPaid", label: "Có lương", sortable: true, format: "boolean", width: "130px" },
    ],
    filters: [
      { key: "isPaid", label: "Có hưởng lương", type: "select", options: yesNoOptions, placeholder: "Tất cả" },
    ],
    fields: [
      { key: "holidayDate", label: "Ngày nghỉ", type: "date", required: true, section: "Thông tin ngày nghỉ" },
      { key: "name", label: "Tên ngày nghỉ", type: "text", required: true, section: "Thông tin ngày nghỉ" },
      { key: "isPaid", label: "Có hưởng lương", type: "checkbox", section: "Cấu hình" },
    ],
    detailFields: [
      { key: "holidayDate", label: "Ngày nghỉ", format: "date" },
      { key: "name", label: "Tên ngày nghỉ" },
      { key: "isPaid", label: "Có hưởng lương", format: "boolean" },
    ],
    metrics: [
      { label: "Tổng ngày nghỉ", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Có lương", getValue: (records) => formatNumber(records.filter((item) => item.isPaid).length) },
    ],
  },
  {
    key: "income-types",
    title: "Loại thu nhập",
    description: "Quản lý loại thu nhập, trạng thái chịu thuế và đánh dấu khoản hoa hồng.",
    primaryAction: "Thêm loại thu nhập",
    apiPath: "/api/income-types",
    searchPlaceholder: "Tìm theo mã hoặc tên loại thu nhập...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "140px" },
      { key: "name", label: "Tên loại thu nhập", sortable: true, width: "260px" },
      { key: "taxability", label: "Thuế", sortable: true, format: "status", width: "130px" },
      { key: "isCommission", label: "Hoa hồng", sortable: true, format: "boolean", width: "130px" },
      { key: "isSystem", label: "Hệ thống", format: "boolean", width: "120px" },
      { key: "isActive", label: "Hoạt động", sortable: true, format: "boolean", width: "130px" },
    ],
    filters: [
      { key: "taxability", label: "Thuế", type: "select", options: taxabilityOptions, placeholder: "Tất cả" },
      { key: "isCommission", label: "Hoa hồng", type: "select", options: yesNoOptions, placeholder: "Tất cả" },
      { key: "isActive", label: "Hoạt động", type: "select", options: yesNoOptions, placeholder: "Tất cả" },
    ],
    fields: [
      { key: "code", label: "Mã loại thu nhập", type: "text", required: true, section: "Thông tin loại thu nhập" },
      { key: "name", label: "Tên loại thu nhập", type: "text", required: true, section: "Thông tin loại thu nhập" },
      { key: "taxability", label: "Tính thuế", type: "select", section: "Cấu hình", options: taxabilityOptions },
      { key: "isCommission", label: "Là khoản hoa hồng", type: "checkbox", section: "Cấu hình" },
      { key: "isSystem", label: "Loại hệ thống", type: "checkbox", section: "Cấu hình" },
      { key: "isActive", label: "Đang hoạt động", type: "checkbox", section: "Trạng thái" },
    ],
    detailFields: [
      { key: "code", label: "Mã loại thu nhập" },
      { key: "name", label: "Tên loại thu nhập" },
      { key: "taxability", label: "Tính thuế", format: "status" },
      { key: "isCommission", label: "Là khoản hoa hồng", format: "boolean" },
      { key: "isSystem", label: "Loại hệ thống", format: "boolean" },
      { key: "isActive", label: "Hoạt động", format: "boolean" },
    ],
    metrics: [
      { label: "Tổng loại thu nhập", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Hoa hồng", getValue: (records) => formatNumber(records.filter((item) => item.isCommission).length) },
      { label: "Đang hoạt động", getValue: (records) => formatNumber(records.filter((item) => item.isActive).length) },
    ],
  },
  {
    key: "deduction-types",
    title: "Loại khấu trừ",
    description: "Quản lý danh mục các khoản khấu trừ dùng trong bảng lương và điều chỉnh kỳ.",
    primaryAction: "Thêm loại khấu trừ",
    apiPath: "/api/deduction-types",
    searchPlaceholder: "Tìm theo mã hoặc tên loại khấu trừ...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã", sortable: true, width: "140px" },
      { key: "name", label: "Tên loại khấu trừ", sortable: true, width: "300px" },
      { key: "isSystem", label: "Hệ thống", format: "boolean", width: "120px" },
      { key: "isActive", label: "Hoạt động", sortable: true, format: "boolean", width: "130px" },
    ],
    filters: [
      { key: "isActive", label: "Hoạt động", type: "select", options: yesNoOptions, placeholder: "Tất cả" },
    ],
    fields: [
      { key: "code", label: "Mã loại khấu trừ", type: "text", required: true, section: "Thông tin loại khấu trừ" },
      { key: "name", label: "Tên loại khấu trừ", type: "text", required: true, section: "Thông tin loại khấu trừ" },
      { key: "isSystem", label: "Loại hệ thống", type: "checkbox", section: "Cấu hình" },
      { key: "isActive", label: "Đang hoạt động", type: "checkbox", section: "Trạng thái" },
    ],
    detailFields: [
      { key: "code", label: "Mã loại khấu trừ" },
      { key: "name", label: "Tên loại khấu trừ" },
      { key: "isSystem", label: "Loại hệ thống", format: "boolean" },
      { key: "isActive", label: "Hoạt động", format: "boolean" },
    ],
    metrics: [
      { label: "Tổng loại khấu trừ", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Đang hoạt động", getValue: (records) => formatNumber(records.filter((item) => item.isActive).length) },
    ],
  },
  {
    key: "policy-overrides",
    title: "Ngoại lệ chính sách",
    description: "Quản lý ngoại lệ lương, phụ cấp, khấu trừ hoặc hoa hồng cá nhân có lý do và hiệu lực.",
    primaryAction: "Thêm ngoại lệ",
    apiPath: "/api/policy-overrides",
    searchPlaceholder: "Tìm theo nhân viên, loại ngoại lệ hoặc lý do...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "employeeName", label: "Nhân viên", sortable: true, width: "220px" },
      { key: "overrideType", label: "Loại ngoại lệ", sortable: true, width: "180px" },
      { key: "incomeTypeName", label: "Thu nhập", width: "180px" },
      { key: "deductionTypeName", label: "Khấu trừ", width: "180px" },
      { key: "amount", label: "Số tiền", sortable: true, format: "money", width: "150px" },
      { key: "rate", label: "Tỷ lệ", sortable: true, width: "100px" },
      { key: "effectiveFrom", label: "Hiệu lực", sortable: true, format: "date", width: "140px" },
      { key: "effectiveTo", label: "Kết thúc", format: "date", width: "140px" },
    ],
    filters: [
      { key: "employeeId", label: "Nhân viên", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân viên" },
      { key: "incomeTypeId", label: "Loại thu nhập", type: "select", options: [], lookupKey: "incomeTypes", placeholder: "Tất cả loại thu nhập" },
      { key: "deductionTypeId", label: "Loại khấu trừ", type: "select", options: [], lookupKey: "deductionTypes", placeholder: "Tất cả loại khấu trừ" },
    ],
    fields: [
      { key: "employeeId", label: "Nhân viên", type: "select", required: true, section: "Liên kết", lookupKey: "employees" },
      { key: "overrideType", label: "Loại ngoại lệ", type: "text", required: true, section: "Thông tin ngoại lệ" },
      { key: "incomeTypeId", label: "Loại thu nhập", type: "select", section: "Thông tin ngoại lệ", lookupKey: "incomeTypes" },
      { key: "deductionTypeId", label: "Loại khấu trừ", type: "select", section: "Thông tin ngoại lệ", lookupKey: "deductionTypes" },
      { key: "amount", label: "Số tiền", type: "number", section: "Giá trị" },
      { key: "rate", label: "Tỷ lệ", type: "number", section: "Giá trị" },
      { key: "reason", label: "Lý do", type: "textarea", required: true, section: "Duyệt" },
      { key: "approvedBy", label: "Người duyệt", type: "select", section: "Duyệt", lookupKey: "employees" },
      { key: "approvedAt", label: "Ngày duyệt", type: "date", section: "Duyệt" },
      { key: "effectiveFrom", label: "Hiệu lực từ", type: "date", required: true, section: "Hiệu lực" },
      { key: "effectiveTo", label: "Hiệu lực đến", type: "date", section: "Hiệu lực" },
    ],
    detailFields: [
      { key: "employeeName", label: "Nhân viên" },
      { key: "overrideType", label: "Loại ngoại lệ" },
      { key: "incomeTypeName", label: "Loại thu nhập" },
      { key: "deductionTypeName", label: "Loại khấu trừ" },
      { key: "amount", label: "Số tiền", format: "money" },
      { key: "rate", label: "Tỷ lệ" },
      { key: "reason", label: "Lý do" },
      { key: "approvedByName", label: "Người duyệt" },
      { key: "approvedAt", label: "Ngày duyệt", format: "date" },
      { key: "effectiveFrom", label: "Hiệu lực từ", format: "date" },
      { key: "effectiveTo", label: "Hiệu lực đến", format: "date" },
    ],
    metrics: [
      { label: "Tổng ngoại lệ", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Đang hiệu lực", getValue: (records) => formatNumber(records.filter((item) => !item.effectiveTo).length) },
    ],
  },
];

export const defaultHrModule = hrModules[0];
