import { formatCurrency, formatNumber } from "@/lib/formatters";
import type { HrModuleConfig } from "./types";

const employeeStatusOptions = [
  { label: "Đang làm", value: "active" },
  { label: "Thử việc", value: "probation" },
  { label: "Tạm ngưng", value: "inactive" },
  { label: "Đã nghỉ", value: "terminated" },
];

const contractTypeOptions = [
  { label: "Full-time", value: "full_time" },
  { label: "Part-time", value: "part_time" },
  { label: "Thử việc", value: "probation" },
  { label: "Cộng tác viên", value: "contractor" },
  { label: "Khác", value: "other" },
];

const salaryPaymentTypeOptions = [
  { label: "Gross", value: "gross" },
  { label: "Net", value: "net" },
];

export const hrModules: HrModuleConfig[] = [
  {
    key: "departments",
    title: "Phòng ban",
    description: "Quản lý phòng ban, phòng cha và trưởng phòng để làm nền cho phân quyền, KPI và bảng lương.",
    primaryAction: "Thêm phòng ban",
    apiPath: "/api/departments",
    searchPlaceholder: "Tìm theo mã hoặc tên phòng ban...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "code", label: "Mã phòng", sortable: true, width: "140px" },
      { key: "name", label: "Tên phòng ban", sortable: true, width: "260px" },
      { key: "parentDepartmentName", label: "Phòng cha", sortable: true, width: "220px" },
      { key: "managerEmployeeName", label: "Trưởng phòng", sortable: true, width: "220px" },
      { key: "description", label: "Mô tả", width: "360px" },
    ],
    filters: [],
    fields: [
      { key: "code", label: "Mã phòng ban", type: "text", required: true, section: "Thông tin phòng ban" },
      { key: "name", label: "Tên phòng ban", type: "text", required: true, section: "Thông tin phòng ban" },
      { key: "parentDepartmentId", label: "Phòng cha", type: "select", section: "Cấu trúc", lookupKey: "departments" },
      { key: "managerEmployeeId", label: "Trưởng phòng", type: "select", section: "Cấu trúc", lookupKey: "employees" },
      { key: "description", label: "Mô tả", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã phòng ban" },
      { key: "name", label: "Tên phòng ban" },
      { key: "parentDepartmentName", label: "Phòng cha" },
      { key: "managerEmployeeName", label: "Trưởng phòng" },
      { key: "description", label: "Mô tả" },
    ],
    metrics: [
      { label: "Tổng phòng ban", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Có trưởng phòng", getValue: (records) => formatNumber(records.filter((item) => item.managerEmployeeId).length) },
    ],
  },
  {
    key: "job-levels",
    title: "Bậc chức danh",
    description: "Quản lý bậc, chức danh và thứ tự cấp bậc dùng cho cơ cấu nhân sự và chính sách lương.",
    primaryAction: "Thêm bậc",
    apiPath: "/api/job-levels",
    searchPlaceholder: "Tìm theo mã hoặc tên bậc...",
    defaultSortBy: "rankOrder",
    columns: [
      { key: "code", label: "Mã bậc", sortable: true, width: "140px" },
      { key: "name", label: "Tên bậc/chức danh", sortable: true, width: "280px" },
      { key: "rankOrder", label: "Thứ tự", sortable: true, width: "140px" },
      { key: "description", label: "Mô tả", width: "420px" },
    ],
    filters: [],
    fields: [
      { key: "code", label: "Mã bậc", type: "text", required: true, section: "Thông tin bậc" },
      { key: "name", label: "Tên bậc/chức danh", type: "text", required: true, section: "Thông tin bậc" },
      { key: "rankOrder", label: "Thứ tự cấp bậc", type: "number", section: "Cấu hình" },
      { key: "description", label: "Mô tả", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "code", label: "Mã bậc" },
      { key: "name", label: "Tên bậc/chức danh" },
      { key: "rankOrder", label: "Thứ tự" },
      { key: "description", label: "Mô tả" },
    ],
    metrics: [
      { label: "Tổng bậc", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Thứ tự cao nhất", getValue: (records) => formatNumber(Math.max(0, ...records.map((item) => Number(item.rankOrder ?? 0)))) },
    ],
  },
  {
    key: "employees",
    title: "Nhân viên",
    description: "Quản lý hồ sơ nhân viên, phòng ban, bậc chức danh và hợp đồng hiện hành để làm dữ liệu gốc.",
    primaryAction: "Thêm nhân viên",
    apiPath: "/api/employees",
    searchPlaceholder: "Tìm theo mã NV, họ tên, email, SĐT...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "employeeCode", label: "Mã NV", sortable: true, width: "120px" },
      { key: "fullName", label: "Họ tên", sortable: true, width: "220px" },
      { key: "departmentName", label: "Phòng ban", sortable: true, width: "180px" },
      { key: "jobLevelName", label: "Bậc", sortable: true, width: "180px" },
      { key: "contractType", label: "Loại HĐ", sortable: true, format: "status", width: "140px" },
      { key: "salaryPaymentType", label: "Gross/Net", sortable: true, format: "status", width: "120px" },
      { key: "baseSalary", label: "Lương cơ bản", sortable: true, format: "money", width: "170px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
      { key: "hireDate", label: "Ngày vào", sortable: true, format: "date", width: "140px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: employeeStatusOptions, placeholder: "Tất cả trạng thái" },
      { key: "departmentId", label: "Phòng ban", type: "select", options: [], lookupKey: "departments", placeholder: "Tất cả phòng ban" },
      { key: "jobLevelId", label: "Bậc", type: "select", options: [], lookupKey: "jobLevels", placeholder: "Tất cả bậc" },
      { key: "contractType", label: "Loại HĐ", type: "select", options: contractTypeOptions, placeholder: "Tất cả loại HĐ" },
      { key: "salaryPaymentType", label: "Gross/Net", type: "select", options: salaryPaymentTypeOptions, placeholder: "Tất cả hình thức" },
    ],
    fields: [
      { key: "employeeCode", label: "Mã nhân viên", type: "text", required: true, section: "Thông tin nhân viên" },
      { key: "fullName", label: "Họ và tên", type: "text", required: true, section: "Thông tin nhân viên" },
      { key: "shortName", label: "Tên gọi tắt", type: "text", section: "Thông tin nhân viên" },
      { key: "departmentId", label: "Phòng ban", type: "select", section: "Tổ chức", lookupKey: "departments" },
      { key: "jobLevelId", label: "Bậc/chức danh", type: "select", section: "Tổ chức", lookupKey: "jobLevels" },
      { key: "status", label: "Trạng thái", type: "select", section: "Tổ chức", options: employeeStatusOptions },
      { key: "hireDate", label: "Ngày vào làm", type: "date", section: "Tổ chức" },
      { key: "terminationDate", label: "Ngày nghỉ", type: "date", section: "Tổ chức" },
      { key: "workEmail", label: "Email công việc", type: "text", section: "Liên hệ" },
      { key: "personalEmail", label: "Email cá nhân", type: "text", section: "Liên hệ" },
      { key: "phone", label: "Số điện thoại", type: "text", section: "Liên hệ" },
      { key: "contractType", label: "Loại hợp đồng", type: "select", required: true, section: "Hợp đồng hiện hành", options: contractTypeOptions },
      { key: "salaryPaymentType", label: "Hình thức nhận lương", type: "select", required: true, section: "Hợp đồng hiện hành", options: salaryPaymentTypeOptions },
      { key: "baseSalary", label: "Lương cơ bản", type: "number", section: "Hợp đồng hiện hành" },
      { key: "standardWorkdays", label: "Ngày công chuẩn", type: "number", section: "Hợp đồng hiện hành" },
      { key: "contractEffectiveFrom", label: "Hiệu lực từ", type: "date", section: "Hợp đồng hiện hành" },
      { key: "contractEffectiveTo", label: "Hiệu lực đến", type: "date", section: "Hợp đồng hiện hành" },
      { key: "bankName", label: "Ngân hàng", type: "text", section: "Thanh toán" },
      { key: "bankAccountNumber", label: "Số tài khoản", type: "text", section: "Thanh toán" },
      { key: "bankAccountName", label: "Tên tài khoản", type: "text", section: "Thanh toán" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "employeeCode", label: "Mã nhân viên" },
      { key: "fullName", label: "Họ và tên" },
      { key: "shortName", label: "Tên gọi tắt" },
      { key: "departmentName", label: "Phòng ban" },
      { key: "jobLevelName", label: "Bậc/chức danh" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "hireDate", label: "Ngày vào làm", format: "date" },
      { key: "terminationDate", label: "Ngày nghỉ", format: "date" },
      { key: "workEmail", label: "Email công việc" },
      { key: "personalEmail", label: "Email cá nhân" },
      { key: "phone", label: "Số điện thoại" },
      { key: "contractType", label: "Loại hợp đồng", format: "status" },
      { key: "salaryPaymentType", label: "Hình thức lương", format: "status" },
      { key: "baseSalary", label: "Lương cơ bản", format: "money" },
      { key: "standardWorkdays", label: "Ngày công chuẩn" },
      { key: "contractEffectiveFrom", label: "Hiệu lực từ", format: "date" },
      { key: "contractEffectiveTo", label: "Hiệu lực đến", format: "date" },
      { key: "bankName", label: "Ngân hàng" },
      { key: "bankAccountNumber", label: "Số tài khoản" },
      { key: "bankAccountName", label: "Tên tài khoản" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng nhân viên", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Đang làm trên trang", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
      { label: "Quỹ lương trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.baseSalary ?? 0), 0)) },
    ],
  },
];

export const defaultHrModule = hrModules[0];
