import { formatCurrency, formatNumber } from "@/lib/formatters";
import type { ModuleConfig } from "@/features/shared/components/management/types";

const batchStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Đang rà soát", value: "reviewing" },
  { label: "Đã duyệt", value: "approved" },
  { label: "Đã khóa", value: "locked" },
  { label: "Đã hủy", value: "cancelled" },
];

const taskStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Chờ duyệt", value: "pending_approval" },
  { label: "Đã duyệt", value: "approved" },
  { label: "Hoàn tất", value: "completed" },
  { label: "Đã hủy", value: "cancelled" },
];

const orderStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Đã phát hành", value: "issued" },
  { label: "Thanh toán một phần", value: "partially_paid" },
  { label: "Đã thanh toán", value: "paid" },
  { label: "Đã hủy", value: "cancelled" },
  { label: "Xóa nợ", value: "written_off" },
];

const paymentStatusOptions = [
  { label: "Chưa thanh toán", value: "unpaid" },
  { label: "Thanh toán một phần", value: "partially_paid" },
  { label: "Đã thanh toán", value: "paid" },
  { label: "Thanh toán dư", value: "overpaid" },
];

const orderTypeOptions = [
  { label: "Định kỳ", value: "recurring" },
  { label: "Một lần", value: "one_time" },
  { label: "Điều chỉnh", value: "manual_adjustment" },
];

const revenueSourceOptions = [
  { label: "3M", value: "3m" },
  { label: "TOPA", value: "topa" },
  { label: "Cấn trừ", value: "offset" },
  { label: "Đối tác", value: "partner" },
  { label: "Khác", value: "other" },
];

export const revenueModules: ModuleConfig[] = [
  {
    key: "recurring-batches",
    title: "Doanh thu định kỳ",
    description: "Sinh doanh thu theo từng dòng dịch vụ hợp đồng, duyệt và khóa kỳ doanh thu.",
    primaryAction: "Tạo batch",
    apiPath: "/api/recurring-revenue-batches",
    searchPlaceholder: "Tìm theo mã batch hoặc ghi chú...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "batchCode", label: "Mã batch", sortable: true, width: "160px" },
      { key: "periodStart", label: "Từ ngày", sortable: true, format: "date", width: "140px" },
      { key: "periodEnd", label: "Đến ngày", sortable: true, format: "date", width: "140px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "150px" },
      { key: "orderCount", label: "Số đơn", width: "120px" },
      { key: "totalAmount", label: "Tổng tiền", sortable: true, format: "money", width: "180px" },
      { key: "generatedAt", label: "Đã sinh", format: "date", width: "140px" },
      { key: "lockedAt", label: "Đã khóa", format: "date", width: "140px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: batchStatusOptions },
      { key: "periodStart", label: "Từ kỳ", type: "date" },
      { key: "periodEnd", label: "Đến kỳ", type: "date" },
    ],
    fields: [
      { key: "batchCode", label: "Mã batch", type: "text", required: true, section: "Kỳ doanh thu" },
      { key: "periodStart", label: "Từ ngày", type: "date", required: true, section: "Kỳ doanh thu" },
      { key: "periodEnd", label: "Đến ngày", type: "date", required: true, section: "Kỳ doanh thu" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: batchStatusOptions },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "batchCode", label: "Mã batch" },
      { key: "periodStart", label: "Từ ngày", format: "date" },
      { key: "periodEnd", label: "Đến ngày", format: "date" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "orderCount", label: "Số đơn" },
      { key: "totalAmount", label: "Tổng tiền", format: "money" },
      { key: "generatedAt", label: "Đã sinh", format: "date" },
      { key: "approvedAt", label: "Đã duyệt", format: "date" },
      { key: "lockedAt", label: "Đã khóa", format: "date" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng batch", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Số đơn trên trang", getValue: (records) => formatNumber(records.reduce((sum, item) => sum + Number(item.orderCount ?? 0), 0)) },
      { label: "Tổng tiền trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.totalAmount ?? 0), 0)) },
    ],
    rowActions: [
      { key: "generate", label: "Sinh doanh thu", icon: "play", endpoint: (record) => `/api/recurring-revenue-batches/${record.id}/generate`, confirmTitle: "Sinh doanh thu định kỳ", confirmLabel: "Sinh", hidden: (record) => !["draft", "reviewing"].includes(String(record.status)) },
      { key: "approve", label: "Duyệt batch", icon: "check", variant: "success", endpoint: (record) => `/api/recurring-revenue-batches/${record.id}/approve`, confirmTitle: "Duyệt batch", confirmLabel: "Duyệt", hidden: (record) => !["draft", "reviewing"].includes(String(record.status)) },
      { key: "lock", label: "Khóa batch", icon: "lock", variant: "warning", endpoint: (record) => `/api/recurring-revenue-batches/${record.id}/lock`, confirmTitle: "Khóa batch", confirmLabel: "Khóa", hidden: (record) => record.status !== "approved" },
      { key: "cancel", label: "Hủy batch", icon: "x", variant: "danger", endpoint: (record) => `/api/recurring-revenue-batches/${record.id}/cancel`, confirmTitle: "Hủy batch", confirmLabel: "Hủy", hidden: (record) => ["locked", "cancelled"].includes(String(record.status)) },
    ],
  },
  {
    key: "one-time-tasks",
    title: "Công việc phát sinh",
    description: "Ghi nhận doanh số một lần ngoài hợp đồng, duyệt workflow và sinh order one-time.",
    primaryAction: "Tạo task phát sinh",
    apiPath: "/api/one-time-tasks",
    searchPlaceholder: "Tìm mã task, khách hàng, dịch vụ, mô tả...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "taskCode", label: "Mã task", sortable: true, width: "140px" },
      { key: "customerName", label: "Khách hàng", sortable: true, width: "260px" },
      { key: "serviceName", label: "Dịch vụ", sortable: true, width: "220px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "150px" },
      { key: "taskDate", label: "Ngày", sortable: true, format: "date", width: "130px" },
      { key: "totalAmount", label: "Tổng tiền", sortable: true, format: "money", width: "170px" },
      { key: "responsibleEmployeeName", label: "Phụ trách", width: "180px" },
      { key: "commissionEmployeeName", label: "Hoa hồng", width: "180px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: taskStatusOptions },
      { key: "customerId", label: "Khách hàng", type: "select", lookupKey: "customers" },
      { key: "employeeId", label: "Nhân sự", type: "select", lookupKey: "employees" },
    ],
    fields: [
      { key: "taskCode", label: "Mã task", type: "text", required: true, section: "Thông tin task" },
      { key: "customerId", label: "Khách hàng", type: "select", required: true, section: "Liên kết", lookupKey: "customers" },
      { key: "serviceId", label: "Dịch vụ", type: "select", section: "Liên kết", lookupKey: "services" },
      { key: "responsibleEmployeeId", label: "Nhân sự phụ trách", type: "select", section: "Trách nhiệm", lookupKey: "employees" },
      { key: "commissionEmployeeId", label: "Nhân sự nhận hoa hồng", type: "select", section: "Trách nhiệm", lookupKey: "employees" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: taskStatusOptions },
      { key: "taskDate", label: "Ngày phát sinh", type: "date", required: true, section: "Thông tin task" },
      { key: "description", label: "Mô tả", type: "textarea", required: true, section: "Thông tin task" },
      { key: "quantity", label: "Số lượng", type: "number", section: "Tài chính" },
      { key: "unitPrice", label: "Đơn giá", type: "number", section: "Tài chính" },
      { key: "vatRate", label: "VAT", type: "number", section: "Tài chính" },
      { key: "revenueSource", label: "Nguồn thu", type: "select", section: "Tài chính", options: revenueSourceOptions },
    ],
    detailFields: [
      { key: "taskCode", label: "Mã task" },
      { key: "customerName", label: "Khách hàng" },
      { key: "serviceName", label: "Dịch vụ" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "taskDate", label: "Ngày phát sinh", format: "date" },
      { key: "description", label: "Mô tả" },
      { key: "quantity", label: "Số lượng" },
      { key: "unitPrice", label: "Đơn giá", format: "money" },
      { key: "vatRate", label: "VAT" },
      { key: "totalAmount", label: "Tổng tiền", format: "money" },
      { key: "revenueSource", label: "Nguồn thu", format: "status" },
      { key: "responsibleEmployeeName", label: "Phụ trách" },
      { key: "commissionEmployeeName", label: "Hoa hồng" },
    ],
    metrics: [
      { label: "Tổng task", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Chờ duyệt", getValue: (records) => formatNumber(records.filter((item) => item.status === "pending_approval").length) },
      { label: "Doanh số trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.totalAmount ?? 0), 0)) },
    ],
    rowActions: [
      { key: "submit", label: "Gửi duyệt", icon: "send", endpoint: (record) => `/api/one-time-tasks/${record.id}/submit`, confirmLabel: "Gửi duyệt", hidden: (record) => record.status !== "draft" },
      { key: "approve", label: "Duyệt", icon: "check", variant: "success", endpoint: (record) => `/api/one-time-tasks/${record.id}/approve`, confirmLabel: "Duyệt", hidden: (record) => !["draft", "pending_approval"].includes(String(record.status)) },
      { key: "complete", label: "Hoàn tất", icon: "file", variant: "success", endpoint: (record) => `/api/one-time-tasks/${record.id}/complete`, confirmLabel: "Hoàn tất", hidden: (record) => record.status !== "approved" },
      { key: "cancel", label: "Hủy", icon: "x", variant: "danger", endpoint: (record) => `/api/one-time-tasks/${record.id}/cancel`, confirmLabel: "Hủy", hidden: (record) => !["draft", "pending_approval"].includes(String(record.status)) },
    ],
  },
  {
    key: "orders",
    title: "Đơn hàng",
    description: "Quản lý doanh thu phát sinh, phát hành đơn hàng, công nợ và trạng thái thanh toán.",
    primaryAction: "Tạo đơn hàng",
    apiPath: "/api/orders",
    searchPlaceholder: "Tìm mã đơn, khách hàng, dịch vụ...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "orderNo", label: "Mã đơn", sortable: true, width: "150px" },
      { key: "orderType", label: "Loại", sortable: true, format: "status", width: "130px" },
      { key: "customerName", label: "Khách hàng", sortable: true, width: "260px" },
      { key: "serviceName", label: "Dịch vụ", width: "220px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "150px" },
      { key: "paymentStatus", label: "Thanh toán", sortable: true, format: "status", width: "170px" },
      { key: "documentDate", label: "Chứng từ", sortable: true, format: "date", width: "130px" },
      { key: "dueDate", label: "Đến hạn", sortable: true, format: "date", width: "130px" },
      { key: "totalAmount", label: "Tổng tiền", sortable: true, format: "money", width: "170px" },
      { key: "paidAmount", label: "Đã thu", sortable: true, format: "money", width: "160px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: orderStatusOptions },
      { key: "paymentStatus", label: "Thanh toán", type: "select", options: paymentStatusOptions },
      { key: "orderType", label: "Loại đơn", type: "select", options: orderTypeOptions },
      { key: "customerId", label: "Khách hàng", type: "select", lookupKey: "customers" },
      { key: "partnerId", label: "Đối tác", type: "select", lookupKey: "partners" },
    ],
    fields: [
      { key: "orderNo", label: "Mã đơn hàng", type: "text", required: true, section: "Thông tin đơn" },
      { key: "orderType", label: "Loại đơn", type: "select", section: "Thông tin đơn", options: orderTypeOptions },
      { key: "documentDate", label: "Ngày chứng từ", type: "date", required: true, section: "Thông tin đơn" },
      { key: "dueDate", label: "Ngày đến hạn", type: "date", section: "Thông tin đơn" },
      { key: "customerId", label: "Khách hàng", type: "select", required: true, section: "Liên kết", lookupKey: "customers" },
      { key: "contractId", label: "Hợp đồng", type: "select", section: "Liên kết", lookupKey: "contracts" },
      { key: "contractServiceId", label: "Dòng dịch vụ hợp đồng", type: "select", section: "Liên kết", lookupKey: "contractServices" },
      { key: "serviceId", label: "Dịch vụ", type: "select", section: "Liên kết", lookupKey: "services" },
      { key: "legalEntityId", label: "Pháp nhân", type: "select", section: "Liên kết", lookupKey: "legalEntities" },
      { key: "partnerId", label: "Đối tác", type: "select", section: "Liên kết", lookupKey: "partners" },
      { key: "responsibleEmployeeId", label: "Phụ trách", type: "select", section: "Trách nhiệm", lookupKey: "employees" },
      { key: "commissionEmployeeId", label: "Nhân sự hoa hồng", type: "select", section: "Trách nhiệm", lookupKey: "employees" },
      { key: "revenueSource", label: "Nguồn thu", type: "select", section: "Tài chính", options: revenueSourceOptions },
      { key: "quantity", label: "Số lượng", type: "number", section: "Tài chính" },
      { key: "unitPrice", label: "Đơn giá", type: "number", section: "Tài chính" },
      { key: "vatRate", label: "VAT", type: "number", section: "Tài chính" },
      { key: "sharedRevenueAmount", label: "Doanh thu chia sẻ", type: "number", section: "Tài chính" },
      { key: "partnerPayableAmount", label: "Phải trả đối tác", type: "number", section: "Tài chính" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "orderNo", label: "Mã đơn" },
      { key: "orderType", label: "Loại", format: "status" },
      { key: "customerName", label: "Khách hàng" },
      { key: "contractCode", label: "Hợp đồng" },
      { key: "serviceName", label: "Dịch vụ" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "paymentStatus", label: "Thanh toán", format: "status" },
      { key: "documentDate", label: "Ngày chứng từ", format: "date" },
      { key: "dueDate", label: "Đến hạn", format: "date" },
      { key: "totalAmount", label: "Tổng tiền", format: "money" },
      { key: "paidAmount", label: "Đã thu", format: "money" },
      { key: "partnerPayableAmount", label: "Phải trả đối tác", format: "money" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng đơn", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Tổng tiền trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.totalAmount ?? 0), 0)) },
      { label: "Đã thu trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.paidAmount ?? 0), 0)) },
    ],
    rowActions: [
      { key: "issue", label: "Phát hành", icon: "file", variant: "success", endpoint: (record) => `/api/orders/${record.id}/issue`, confirmTitle: "Phát hành đơn hàng", confirmLabel: "Phát hành", hidden: (record) => record.status !== "draft" },
      { key: "write-off", label: "Xóa nợ", icon: "ban", variant: "warning", endpoint: (record) => `/api/orders/${record.id}/write-off`, confirmTitle: "Xóa nợ đơn hàng", confirmLabel: "Xóa nợ", hidden: (record) => !["issued", "partially_paid", "paid"].includes(String(record.status)) },
      { key: "cancel", label: "Hủy", icon: "x", variant: "danger", endpoint: (record) => `/api/orders/${record.id}/cancel`, confirmTitle: "Hủy đơn hàng", confirmLabel: "Hủy", hidden: (record) => record.status !== "draft" },
    ],
  },
];
