import { formatCurrency, formatNumber } from "@/lib/formatters";
import type { ModuleConfig } from "@/features/shared/components/management/types";

const statusOptions = [
  { label: "Đang hoạt động", value: "active" },
  { label: "Ngưng hoạt động", value: "inactive" },
  { label: "Lưu trữ", value: "archived" },
];

const contractStatusOptions = [
  { label: "Nháp", value: "draft" },
  { label: "Còn hiệu lực", value: "active" },
  { label: "Sắp hết hạn", value: "expiring" },
  { label: "Đã chấm dứt", value: "terminated" },
  { label: "Đã hủy", value: "cancelled" },
];

const billingCycleOptions = [
  { label: "Hàng tháng", value: "monthly" },
  { label: "Hàng quý", value: "quarterly" },
  { label: "Hàng năm", value: "yearly" },
  { label: "Một lần", value: "one_time" },
  { label: "Tùy chỉnh", value: "custom" },
];

export const crmModules: ModuleConfig[] = [
  {
    key: "customers",
    title: "Khách hàng",
    description: "Quản lý thông tin khách hàng, người đại diện, phần mềm kế toán và nhân sự phụ trách.",
    primaryAction: "Thêm khách hàng",
    apiPath: "/api/customers",
    searchPlaceholder: "Tìm theo mã KH, tên công ty, MST, email, SĐT...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "customerCode", label: "Mã KH", sortable: true, width: "120px" },
      { key: "companyName", label: "Tên công ty", sortable: true, width: "260px" },
      { key: "taxCode", label: "MST", sortable: true, width: "150px" },
      { key: "phone", label: "SĐT", width: "140px" },
      { key: "email", label: "Email", width: "220px" },
      { key: "representativeName", label: "Đại diện", width: "180px" },
      { key: "assignedEmployeeName", label: "Phụ trách", width: "180px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "140px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: statusOptions, placeholder: "Tất cả trạng thái" },
      { key: "assignedEmployeeId", label: "Nhân sự", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân sự" },
    ],
    fields: [
      { key: "customerCode", label: "Mã khách hàng", type: "text", required: true, section: "Thông tin định danh" },
      { key: "companyName", label: "Tên công ty", type: "text", required: true, section: "Thông tin định danh" },
      { key: "shortName", label: "Tên gọi tắt", type: "text", section: "Thông tin định danh" },
      { key: "taxCode", label: "Mã số thuế", type: "text", section: "Thông tin định danh" },
      { key: "address", label: "Địa chỉ", type: "textarea", section: "Thông tin định danh" },
      { key: "email", label: "Email", type: "text", section: "Liên hệ" },
      { key: "phone", label: "Số điện thoại", type: "text", section: "Liên hệ" },
      { key: "representativeName", label: "Người đại diện", type: "text", section: "Liên hệ" },
      { key: "representativeTitle", label: "Chức vụ", type: "text", section: "Liên hệ" },
      { key: "accountingSoftware", label: "Phần mềm kế toán", type: "text", section: "Kỹ thuật" },
      { key: "accountingSoftwareUrl", label: "Địa chỉ truy cập phần mềm", type: "text", section: "Kỹ thuật" },
      { key: "assignedEmployeeId", label: "Nhân sự phụ trách", type: "select", section: "Quản trị", lookupKey: "employees" },
      { key: "defaultLegalEntityId", label: "Pháp nhân mặc định", type: "select", section: "Quản trị", lookupKey: "legalEntities" },
      { key: "status", label: "Trạng thái", type: "select", section: "Quản trị", options: statusOptions },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Quản trị" },
    ],
    detailFields: [
      { key: "customerCode", label: "Mã KH" },
      { key: "companyName", label: "Tên công ty" },
      { key: "shortName", label: "Tên gọi tắt" },
      { key: "taxCode", label: "Mã số thuế" },
      { key: "address", label: "Địa chỉ" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Số điện thoại" },
      { key: "representativeName", label: "Người đại diện" },
      { key: "representativeTitle", label: "Chức vụ" },
      { key: "accountingSoftware", label: "Phần mềm kế toán" },
      { key: "accountingSoftwareUrl", label: "Địa chỉ truy cập" },
      { key: "assignedEmployeeName", label: "Nhân sự phụ trách" },
      { key: "defaultLegalEntityName", label: "Pháp nhân mặc định" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng khách hàng", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Đang hoạt động", getValue: (records) => formatNumber(records.filter((item) => item.status === "active").length) },
    ],
  },
  {
    key: "services",
    title: "Dịch vụ",
    description: "Quản lý danh mục dịch vụ, đơn giá chuẩn, loại dịch vụ và trạng thái hoạt động.",
    primaryAction: "Thêm dịch vụ",
    apiPath: "/api/services",
    searchPlaceholder: "Tìm theo mã dịch vụ, tên dịch vụ, loại dịch vụ...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "serviceCode", label: "Mã DV", sortable: true, width: "120px" },
      { key: "name", label: "Tên dịch vụ", sortable: true, width: "280px" },
      { key: "serviceType", label: "Loại dịch vụ", sortable: true, width: "180px" },
      { key: "standardUnitPrice", label: "Đơn giá chuẩn", sortable: true, format: "money", width: "180px" },
      { key: "isActive", label: "Hoạt động", sortable: true, format: "boolean", width: "130px" },
      { key: "description", label: "Mô tả", width: "320px" },
    ],
    filters: [
      {
        key: "isActive",
        label: "Hoạt động",
        type: "select",
        placeholder: "Tất cả",
        options: [
          { label: "Đang hoạt động", value: "true" },
          { label: "Tạm ẩn", value: "false" },
        ],
      },
    ],
    fields: [
      { key: "serviceCode", label: "Mã dịch vụ", type: "text", required: true, section: "Thông tin dịch vụ" },
      { key: "name", label: "Tên dịch vụ", type: "text", required: true, section: "Thông tin dịch vụ" },
      { key: "serviceType", label: "Loại dịch vụ", type: "text", required: true, section: "Thông tin dịch vụ" },
      { key: "standardUnitPrice", label: "Đơn giá chuẩn", type: "number", section: "Giá" },
      { key: "isActive", label: "Đang hoạt động", type: "checkbox", section: "Trạng thái" },
      { key: "description", label: "Mô tả", type: "textarea", section: "Thông tin dịch vụ" },
    ],
    detailFields: [
      { key: "serviceCode", label: "Mã DV" },
      { key: "name", label: "Tên dịch vụ" },
      { key: "serviceType", label: "Loại dịch vụ" },
      { key: "standardUnitPrice", label: "Đơn giá chuẩn", format: "money" },
      { key: "isActive", label: "Hoạt động", format: "boolean" },
      { key: "description", label: "Mô tả" },
    ],
    metrics: [
      { label: "Tổng dịch vụ", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Đang hoạt động", getValue: (records) => formatNumber(records.filter((item) => item.isActive === true).length) },
    ],
  },
  {
    key: "contracts",
    title: "Hợp đồng",
    description: "Theo dõi hợp đồng dịch vụ, kỳ tính phí, giá trị, trạng thái hiệu lực và nguồn thu.",
    primaryAction: "Thêm hợp đồng",
    apiPath: "/api/contracts",
    searchPlaceholder: "Tìm theo mã hợp đồng, mã KH, tên khách hàng...",
    defaultSortBy: "createdAt",
    columns: [
      { key: "contractCode", label: "Mã HĐ", sortable: true, width: "140px" },
      { key: "customerName", label: "Khách hàng", sortable: true, width: "260px" },
      { key: "status", label: "Trạng thái", sortable: true, format: "status", width: "150px" },
      { key: "billingCycle", label: "Kỳ phí", sortable: true, format: "status", width: "130px" },
      { key: "monthlyFee", label: "Phí tháng", format: "money", width: "160px" },
      { key: "quarterlyFee", label: "Phí quý", format: "money", width: "160px" },
      { key: "contractValue", label: "Giá trị HĐ", sortable: true, format: "money", width: "170px" },
      { key: "effectiveDate", label: "Hiệu lực", sortable: true, format: "date", width: "140px" },
      { key: "terminationDate", label: "Chấm dứt", format: "date", width: "140px" },
      { key: "assignedEmployeeName", label: "Phụ trách", width: "180px" },
    ],
    filters: [
      { key: "status", label: "Trạng thái", type: "select", options: contractStatusOptions, placeholder: "Tất cả trạng thái" },
      { key: "billingCycle", label: "Kỳ phí", type: "select", options: billingCycleOptions, placeholder: "Tất cả kỳ phí" },
      { key: "customerId", label: "Khách hàng", type: "select", options: [], lookupKey: "customers", placeholder: "Tất cả khách hàng" },
      { key: "assignedEmployeeId", label: "Nhân sự", type: "select", options: [], lookupKey: "employees", placeholder: "Tất cả nhân sự" },
    ],
    fields: [
      { key: "contractCode", label: "Mã hợp đồng", type: "text", required: true, section: "Thông tin hợp đồng" },
      { key: "customerId", label: "Khách hàng", type: "select", required: true, section: "Thông tin hợp đồng", lookupKey: "customers" },
      { key: "legalEntityId", label: "Pháp nhân ký", type: "select", section: "Thông tin hợp đồng", lookupKey: "legalEntities" },
      { key: "partnerId", label: "Đối tác", type: "select", section: "Thông tin hợp đồng", lookupKey: "partners" },
      { key: "assignedEmployeeId", label: "Nhân sự phụ trách", type: "select", section: "Thông tin hợp đồng", lookupKey: "employees" },
      { key: "status", label: "Trạng thái", type: "select", section: "Trạng thái", options: contractStatusOptions },
      { key: "billingCycle", label: "Kỳ tính phí", type: "select", section: "Tài chính", options: billingCycleOptions },
      { key: "monthlyFee", label: "Phí dịch vụ hàng tháng", type: "number", section: "Tài chính" },
      { key: "quarterlyFee", label: "Phí hàng quý", type: "number", section: "Tài chính" },
      { key: "contractValue", label: "Giá trị hợp đồng", type: "number", section: "Tài chính" },
      { key: "vatRate", label: "VAT", type: "number", section: "Tài chính" },
      { key: "paymentDueDays", label: "Hạn thanh toán (ngày)", type: "number", section: "Tài chính" },
      { key: "billingStartDate", label: "Bắt đầu tính phí", type: "date", section: "Hiệu lực" },
      { key: "effectiveDate", label: "Ngày hiệu lực", type: "date", required: true, section: "Hiệu lực" },
      { key: "termYears", label: "Số năm hiệu lực", type: "number", section: "Hiệu lực" },
      { key: "terminationDate", label: "Ngày chấm dứt", type: "date", section: "Hiệu lực" },
      { key: "notes", label: "Ghi chú", type: "textarea", section: "Ghi chú" },
    ],
    detailFields: [
      { key: "contractCode", label: "Mã hợp đồng" },
      { key: "customerName", label: "Khách hàng" },
      { key: "legalEntityName", label: "Pháp nhân" },
      { key: "partnerName", label: "Đối tác" },
      { key: "assignedEmployeeName", label: "Nhân sự phụ trách" },
      { key: "status", label: "Trạng thái", format: "status" },
      { key: "billingCycle", label: "Kỳ tính phí", format: "status" },
      { key: "monthlyFee", label: "Phí tháng", format: "money" },
      { key: "quarterlyFee", label: "Phí quý", format: "money" },
      { key: "contractValue", label: "Giá trị hợp đồng", format: "money" },
      { key: "vatRate", label: "VAT" },
      { key: "paymentDueDays", label: "Hạn thanh toán" },
      { key: "billingStartDate", label: "Bắt đầu tính phí", format: "date" },
      { key: "effectiveDate", label: "Ngày hiệu lực", format: "date" },
      { key: "termYears", label: "Số năm hiệu lực" },
      { key: "terminationDate", label: "Ngày chấm dứt", format: "date" },
      { key: "notes", label: "Ghi chú" },
    ],
    metrics: [
      { label: "Tổng hợp đồng", getValue: (_records, pagination) => formatNumber(pagination?.total ?? 0) },
      { label: "Trên trang này", getValue: (records) => formatNumber(records.length) },
      { label: "Giá trị trên trang", getValue: (records) => formatCurrency(records.reduce((sum, item) => sum + Number(item.contractValue ?? 0), 0)) },
    ],
  },
];

export const defaultModule = crmModules[0];
