import type { ReactNode } from "react";

const labels: Record<string, string> = {
  active: "Đang hoạt động",
  inactive: "Ngưng hoạt động",
  archived: "Lưu trữ",
  draft: "Nháp",
  calculated: "Đã tính",
  reviewing: "Đang rà soát",
  pending: "Chờ duyệt",
  pending_approval: "Chờ duyệt",
  approved: "Đã duyệt",
  locked: "Đã khóa",
  rejected: "Từ chối",
  expiring: "Sắp hết hạn",
  terminated: "Chấm dứt",
  cancelled: "Đã hủy",
  probation: "Thử việc",
  full_time: "Full-time",
  part_time: "Part-time",
  contractor: "Cộng tác viên",
  other: "Khác",
  gross: "Gross",
  net: "Net",
  taxable: "Chịu thuế",
  non_taxable: "Miễn thuế",
  monthly: "Hàng tháng",
  quarterly: "Hàng quý",
  yearly: "Hàng năm",
  one_time: "Một lần",
  recurring: "Định kỳ",
  manual_adjustment: "Điều chỉnh",
  custom: "Tùy chỉnh",
  issued: "Đã phát hành",
  partially_paid: "Thanh toán một phần",
  paid: "Đã thanh toán",
  written_off: "Xóa nợ",
  unpaid: "Chưa thanh toán",
  overpaid: "Thanh toán dư",
  bank_transfer: "Chuyển khoản",
  cash: "Tiền mặt",
  offset: "Cấn trừ",
  "3m": "3M",
  topa: "TOPA",
  partner: "Đối tác",
  order_debit: "Ghi nợ đơn hàng",
  payment_credit: "Thu tiền",
  adjustment_debit: "Điều chỉnh tăng",
  adjustment_credit: "Điều chỉnh giảm",
  write_off: "Xóa nợ",
  opening_balance: "Số dư đầu kỳ",
  payable: "Phải trả",
  receivable: "Phải thu",
  collection_on_behalf: "Thu hộ",
  confirmed: "Đã xác nhận",
  completed: "Hoàn tất",
};

const styles: Record<string, string> = {
  active: "border-emerald-200 bg-emerald-50 text-emerald-700",
  inactive: "border-zinc-200 bg-zinc-50 text-zinc-600",
  archived: "border-zinc-200 bg-zinc-100 text-zinc-600",
  draft: "border-amber-200 bg-amber-50 text-amber-700",
  calculated: "border-blue-200 bg-blue-50 text-blue-700",
  reviewing: "border-sky-200 bg-sky-50 text-sky-700",
  pending: "border-amber-200 bg-amber-50 text-amber-700",
  pending_approval: "border-amber-200 bg-amber-50 text-amber-700",
  approved: "border-emerald-200 bg-emerald-50 text-emerald-700",
  locked: "border-zinc-300 bg-zinc-100 text-zinc-700",
  rejected: "border-red-200 bg-red-50 text-red-700",
  expiring: "border-orange-200 bg-orange-50 text-orange-700",
  terminated: "border-red-200 bg-red-50 text-red-700",
  cancelled: "border-red-200 bg-red-50 text-red-700",
  probation: "border-sky-200 bg-sky-50 text-sky-700",
  full_time: "border-emerald-200 bg-emerald-50 text-emerald-700",
  part_time: "border-blue-200 bg-blue-50 text-blue-700",
  contractor: "border-purple-200 bg-purple-50 text-purple-700",
  other: "border-zinc-200 bg-zinc-50 text-zinc-600",
  gross: "border-indigo-200 bg-indigo-50 text-indigo-700",
  net: "border-teal-200 bg-teal-50 text-teal-700",
  taxable: "border-orange-200 bg-orange-50 text-orange-700",
  non_taxable: "border-emerald-200 bg-emerald-50 text-emerald-700",
  monthly: "border-blue-200 bg-blue-50 text-blue-700",
  quarterly: "border-violet-200 bg-violet-50 text-violet-700",
  yearly: "border-cyan-200 bg-cyan-50 text-cyan-700",
  one_time: "border-fuchsia-200 bg-fuchsia-50 text-fuchsia-700",
  recurring: "border-blue-200 bg-blue-50 text-blue-700",
  manual_adjustment: "border-amber-200 bg-amber-50 text-amber-700",
  custom: "border-slate-200 bg-slate-50 text-slate-700",
  issued: "border-blue-200 bg-blue-50 text-blue-700",
  partially_paid: "border-amber-200 bg-amber-50 text-amber-700",
  paid: "border-emerald-200 bg-emerald-50 text-emerald-700",
  written_off: "border-zinc-300 bg-zinc-100 text-zinc-700",
  unpaid: "border-red-200 bg-red-50 text-red-700",
  overpaid: "border-purple-200 bg-purple-50 text-purple-700",
  bank_transfer: "border-blue-200 bg-blue-50 text-blue-700",
  cash: "border-emerald-200 bg-emerald-50 text-emerald-700",
  offset: "border-violet-200 bg-violet-50 text-violet-700",
  "3m": "border-zinc-300 bg-zinc-50 text-zinc-700",
  topa: "border-cyan-200 bg-cyan-50 text-cyan-700",
  partner: "border-indigo-200 bg-indigo-50 text-indigo-700",
  order_debit: "border-red-200 bg-red-50 text-red-700",
  payment_credit: "border-emerald-200 bg-emerald-50 text-emerald-700",
  adjustment_debit: "border-orange-200 bg-orange-50 text-orange-700",
  adjustment_credit: "border-teal-200 bg-teal-50 text-teal-700",
  write_off: "border-zinc-300 bg-zinc-100 text-zinc-700",
  opening_balance: "border-slate-200 bg-slate-50 text-slate-700",
  payable: "border-red-200 bg-red-50 text-red-700",
  receivable: "border-emerald-200 bg-emerald-50 text-emerald-700",
  collection_on_behalf: "border-blue-200 bg-blue-50 text-blue-700",
  confirmed: "border-blue-200 bg-blue-50 text-blue-700",
  completed: "border-emerald-200 bg-emerald-50 text-emerald-700",
};

export function StatusBadge({ value }: { value: ReactNode }) {
  const key = String(value ?? "");

  return (
    <span
      className={`inline-flex h-6 items-center rounded-full border px-2 text-xs font-medium ${
        styles[key] ?? "border-zinc-200 bg-zinc-50 text-zinc-600"
      }`}
    >
      {labels[key] ?? (key || "Chưa có")}
    </span>
  );
}
